### ISSUE TITLE
upgrade angular 6 core, material, and cli

### ISSUE THREAD

**Issue by mushinlogit** [unfetter-discover/unfetter#1011]
Angular 6 is out `https://blog.angular.io/version-6-of-angular-now-available-cc56b0efa7a4`

## done upgrade packages to work with Angular 6
- [x] upgrade core angular 6
- [x] upgrade angular cli to sync w/ angular 6 (maybe do this one first?)
- [x] upgrade ngrx to work w/ latest angular 6
- [x] upgrade angular material to work w/ latest angular 6

related to unfetter-discover/unfetter#997
The linter does not seem to be configurable either
`https://angular.io/guide/styleguide#05-13`
`http://codelyzer.com/rules/no-input-rename/`

# lint errors
ERROR: /Users/---/git/unfetter-discover/unfetter-ui/src/app/global/components/risk-breakdown/risk-breakdown.component.ts[18, 5]: In the class "RiskBreakdownComponent", the directive input property "riskBreakdown" should not be renamed.
ERROR: /Users/---/git/unfetter-discover/unfetter-ui/src/app/global/components/risk-icon/risk-icon.component.ts[10, 3]: In the class "RiskIconComponent", the directive input property "risk" should not be renamed.
ERROR: /Users/---/git/unfetter-discover/unfetter-ui/src/app/global/components/risk-icon/risk-icon.component.ts[11, 3]: In the class "RiskIconComponent", the directive input property "showTooltip" should not be renamed.
ERROR: /Users/---/git/unfetter-discover/unfetter-ui/src/app/global/components/risk-icon/risk-icon.component.ts[12, 3]: In the class "RiskIconComponent", the directive input property "tooltipPlacement" should not be renamed.
ERROR: /Users/---/git/unfetter-discover/unfetter-ui/src/app/global/components/risk-icon/risk-icon.component.ts[13, 3]: In the class "RiskIconComponent", the directive input property "showTextShadow" should not be renamed.
ERROR: /Users/---/git/unfetter-discover/unfetter-ui/src/app/global/components/sidepanel/sidepanel-list-item.component.ts[12, 3]: In the class "SidepanelListItemComponent", the directive input property "label" should not be renamed.
ERROR: /Users/---/git/unfetter-discover/unfetter-ui/src/app/global/components/sidepanel/sidepanel-list-item.component.ts[14, 3]: In the class "SidepanelListItemComponent", the directive input property "icon" should not be renamed.
ERROR: /Users/---/git/unfetter-discover/unfetter-ui/src/app/global/components/sidepanel/sidepanel-list-item.component.ts[16, 3]: In the class "SidepanelListItemComponent", the directive input property "items" should not be renamed.
ERROR: /Users/---/git/unfetter-discover/unfetter-ui/src/app/global/components/sidepanel/sidepanel-list-item.component.ts[18, 3]: In the class "SidepanelListItemComponent", the directive input property "expandable" should not be renamed.
ERROR: /Users/---/git/unfetter-discover/unfetter-ui/src/app/global/components/sidepanel/sidepanel-list-item.component.ts[20, 3]: In the class "SidepanelListItemComponent", the directive input property "showCount" should not be renamed.
ERROR: /Users/---/git/unfetter-discover/unfetter-ui/src/app/global/components/sidepanel/sidepanel-list-item.component.ts[22, 3]: In the class "SidepanelListItemComponent", the directive input property "expanded" should not be renamed.
ERROR: /Users/---/git/unfetter-discover/unfetter-ui/src/app/global/components/sidepanel/sidepanel-list-item.component.ts[24, 3]: In the class "SidepanelListItemComponent", the directive input property "hideToggle" should not be renamed.
ERROR: /Users/---/git/unfetter-discover/unfetter-ui/src/app/global/components/sidepanel/sidepanel-option-item.component.ts[10, 3]: In the class "SidepanelOptionItemComponent", the directive input property "label" should not be renamed.
ERROR: /Users/---/git/unfetter-discover/unfetter-ui/src/app/global/components/sidepanel/sidepanel-option-item.component.ts[12, 3]: In the class "SidepanelOptionItemComponent", the directive input property "icon" should not be renamed.
ERROR: /Users/---/git/unfetter-discover/unfetter-ui/src/app/global/components/sidepanel/sidepanel-option-item.component.ts[14, 3]: In the class "SidepanelOptionItemComponent", the directive input property "disabled" should not be renamed.
ERROR: /Users/---/git/unfetter-discover/unfetter-ui/src/app/assess/v2/result/summary/summary-report/sophistication-breakdown/sophistication-breakdown.component.ts[12, 3]: In the class "SophisticationBreakdownComponent", the directive input property "assessedAttackP
ERROR: /Users/---/git/unfetter-discover/unfetter-ui/src/app/assess/v2/result/summary/summary-report/sophistication-breakdown/sophistication-breakdown.component.ts[13, 3]: In the class "SophisticationBreakdownComponent", the directive input property "allAttackPatter
ERROR: /Users/---/git/unfetter-discover/unfetter-ui/src/app/assess/v3/result/summary/summary-report/sophistication-breakdown/sophistication-breakdown.component.ts[12, 3]: In the class "SophisticationBreakdownComponent", the directive input property "assessedAttackP
ERROR: /Users/---/git/unfetter-discover/unfetter-ui/src/app/assess/v3/result/summary/summary-report/sophistication-breakdown/sophistication-breakdown.component.ts[13, 3]: In the class "SophisticationBreakdownComponent", the directive input property "allAttackPatter
ERROR: /Users/---/git/unfetter-discover/unfetter-ui/src/app/baseline/result/summary/summary-report/sophistication-breakdown/sophistication-breakdown.component.ts[12, 3]: In the class "SophisticationBreakdownComponent", the directive input property "assessedAttackPa
ERROR: /Users/---/git/unfetter-discover/unfetter-ui/src/app/baseline/result/summary/summary-report/sophistication-breakdown/sophistication-breakdown.component.ts[13, 3]: In the class "SophisticationBreakdownComponent", the directive input property "allAttackPattern
ERROR: /Users/---/git/unfetter-discover/unfetter-ui/src/app/threat-dashboard/export/export.component.ts[15, 3]: In the class "ExportComponent", the directive input property "threatReport" should not be renamed.
ERROR: /Users/---/git/unfetter-discover/unfetter-ui/src/app/threat-dashboard/kill-chain-table/kill-chain-table.component.ts[44, 3]: In the class "KillChainTableComponent", the directive input property "threatReport" should not be renamed.
ERROR: /Users/---/git/unfetter-discover/unfetter-ui/src/app/threat-dashboard/kill-chain-table/kill-chain-table.component.ts[46, 3]: In the class "KillChainTableComponent", the directive input property "attackPatterns" should not be renamed.
ERROR: /Users/---/git/unfetter-discover/unfetter-ui/src/app/threat-dashboard/kill-chain-table/kill-chain-table.component.ts[48, 3]: In the class "KillChainTableComponent", the directive input property "intrusionSetsDashboard" should not be renamed.

**Comment by j987987** [comment]
- `ng update` didn't work for `@angular/material`
- Angular material 6 changed some styling inside of tables
- rxjs `partition` was pretty much removed (it was changed to a state that pretty much makes it useless)
- Many options were changed on ng serve/build, basically, it seems like they wanted more complex build/serve options in `configurations` in the new `angular.json`
