### ISSUE TITLE
Add ability to create "sections" of text when creating analytics

### ISSUE THREAD

**Issue by infosec-alchemist** [unfetter-discover/unfetter#1037]
Design and develop ability to allow users to enter markuped text in a text area, and allow for "Sections" to be created that can be created.

Similar to a Wiki markup when an "#" is used to separate text groups.

Evaluate technical options with the design team.  Provide samples here for discussion.

Technique should be able to be added to other main objects that are created by users in Unfetter.

**Comment by webiator** [comment]
Some markdown editors: `https://ourcodeworld.com/articles/read/359/top-7-best-markdown-editors-javascript-and-jquery-plugins`

Some "standard" markdown libraries: CommonMark, markedjs, markdown-it, Remarkable, Showdown. (Showdown is the first to pop up in multiple searches, all but Remarkable appears to be very active in development.)

**Comment by infosec-alchemist** [comment]
With these markdown editors, can we extract and split the sections up in the backend if we find it necessary?

also, would it be difficult to add our own markups?  A thought would be we could do something like $attack-pattern-ex and that would be the attack pattern being described, which we could then create a link to. 

We don't have to do this in the first go around, but its something that I think we will want to do in the future.

**Comment by webiator** [comment]
Two editors, markdown-it and Editor.md, appear to have the ability to create custom markdown, though not sure how easy it is to implement from the write-up. To reduce the number of libraries we pull in, I'm hoping one of those libraries can just be used to view the markdown, too, not just edit it.

**Comment by webiator** [comment]
A simple markdown library for Angular was added, ngx-markdown. Based on discussions, this may be a good start, but something closer to a wiki editor may be preferred. Will do a quick search of possible libraries to determine what may be possible.

**Comment by mpmmasterpeace** [comment]
What is left to do on this issue?

**Comment by webiator** [comment]
Closing this ticket as OBE. We don't have a way to implement this, but we are constantly creating better and better interfaces for our users, such as #1377.
