### ISSUE TITLE
TAXII Server Bug: Objects endpoint does not allow URL filter parameters 

### ISSUE THREAD

**Issue by jordan2175** [unfetter-discover/unfetter#1050]
The objects endpoint does not honor the URL filter parameters.  This is similar to the issue for the manifest resource. This is opened as a separate issue, as your http handler code might be different for each endpoint.

If you hit this URL
https://cti-taxii.mitre.org/stix/collections/95ecc380-afe9-11e4-9b6c-751b66dd541e/objects/

The server does not honor the following URL parameters
?id=...
?type=...
?version=...

**Comment by j987987** [comment]
Thanks for the feedback, jordan.

In the current version of the TAXII 2.0 spec, those parameters were moved to the `match[]` field.  For more information, see: http://docs.oasis-open.org/cti/taxii/v2.0/cs01/taxii-v2.0-cs01.html#_Toc496542720

Let us know if the the `match[id]` and `match[type]` parameters work for you please.

**Comment by jordan2175** [comment]
Please disregard.
