### ISSUE TITLE
Deployments: Add polyfills to unfetter-ui

### ISSUE THREAD

**Issue by mushinlogit** [unfetter-discover/unfetter#1063]
## problem
To deploy our ui to a wider audience we may need to add additional polyfills to unfetter-ui.  Track some of the needed polyfills here

## done 
add polyfills  in `unfetter-ui/*/polyfills.ts`, test against some old target browsers

**Comment by webiator** [comment]
Probably will want polyfill for
- array (for Array.from)
- set
- map
- object
