### ISSUE TITLE
Change label of "pattern" on analytic exchange

### ISSUE THREAD

**Issue by infosec-alchemist** [unfetter-discover/unfetter#1064]
For the analytic exchange, on the 'pattern' data input, change the label to 'pseudocode'.  Also, put a note that says "use a stix pattern to get automated translations"

Users are confused about the stix pattern, if they aren't familiar with stix.  Using "pseudocode", with a highlight that using the stix pattern will open up more features, will make it easier to understand.

**Comment by j987987** [comment]
Pushed to develop

https://github.com/unfetter-discover/unfetter-ui/commit/66d77eb0424655ef7fc8c92358d593cac4dab9ab
