### ISSUE TITLE
Remove authServices array from angular environment files

### ISSUE THREAD

**Issue by j987987** [unfetter-discover/unfetter#1093]
Currently, the `api_configuration_tool.py` script will write `authServices` to the UI's `environment.uac.ts` (development) and `environment.prod.ts` (deploy) files.  However, these environment files are checked into git, thus if a user uses something different from git, he/she risks losing those configurations when pulling code, and there is risk of the two separate files losing synchronization of settings.

One suggestion would be to have `api_configuration_tool.py` write to a git ignored json file in the UI's assets directory -- but there are other ways to solve this issue.

**Comment by webiator** [comment]
`environment.uac.ts` is an invention of our run mode, and is non-standard angular, so it is certainly a candidate for gitignore. That said, however, there's a dev and prod environment for a reason, and I agree we shouldn't overwrite them, ever. I recognized this as a problem, and didn't spend time thinking of alternatives. We would need a "UAC" and "Demo" configuration, regardless of whether we are in dev or prod mode, so I think these settings should go somewhere other than the environment.ts files.
