### ISSUE TITLE
Blank heatmap on analytic exchange

### ISSUE THREAD

**Issue by infosec-alchemist** [unfetter-discover/unfetter#1110]
When I open the analytic exchange, the heatmap is always blank. I have to refresh the page to get it to work
![image](https://user-images.githubusercontent.com/19472140/40941863-507f25b2-681a-11e8-9c56-6997728a16ec.png)

**Comment by webiator** [comment]
This happens on startup. The data is being loaded asynchronously, but it's not triggering an update.
