### ISSUE TITLE
Analytic Exchange filter has two "Credential dumping" attack patterns

### ISSUE THREAD

**Issue by infosec-alchemist** [unfetter-discover/unfetter#1113]
On my system, from a clean install and new database, there are two attack patterns in the Analytic Exchange filter list that are called Credential Dumping.

One had the "d" in capital.  There should only be one.  This might be a problem with loading the two frameworks?

![image](https://user-images.githubusercontent.com/19472140/40942286-bb9f17b6-681b-11e8-8172-41ca1f61213b.png)

**Comment by webiator** [comment]
There are actually a large number of duplicates like this. My guess is, the frameworks have similarly-named attack patterns, different only in one using title case.

**Comment by j987987** [comment]
Even if they had the same casing, both would be displayed as they're two separate attack patterns both with unique IDs (the filter cares about ID, the name is only for presentation.)

Possible solutions:
- Only display attack patterns with phases in the preferred threat framework (currently the filter shows all attack patterns in the system.)
- Add a way to indicate which threat framework(s) each attack pattern belongs to (preferably some type of icon or badge to keep size to a minimum)
- Only show unique names (ignoring casing), and if two attack patterns are merged on name, include the ID for both in the filter
- Do nothing, and assume user deployments will only have attack patterns loaded from a single framework

**Comment by infosec-alchemist** [comment]
Okay, so I think a couple of things should happen

- [ ] The ones with similar names, we just default to the ATT&CK version and not have similar items.  We need to go through and see which ones are duplicated
- [ ] We should only show the attack patterns for the currently selected preferred framework.  I think we should be able to change that, but it would be site wide.   My hypothesis is that most people will not be switching back and forth
- [ ] I like the idea that we do a case insensitive evaluation of the title to see if we are ingesting the same attack pattern or not.

**Comment by j987987** [comment]
Step #2 complete https://github.com/unfetter-discover/unfetter-ui/pull/495
