### ISSUE TITLE
Implement squash in our deployments

### ISSUE THREAD

**Issue by infosec-alchemist** [unfetter-discover/unfetter#1118]
Squashing during the docker build should remove the intermediate layers, reduce size, and make it easier to move the docker images around.

Implement squash and possibly update our production builds.  

https://docs.docker.com/engine/reference/commandline/image_build/

**Comment by mushinlogit** [comment]
We use docker compose to build our docker hub images and docker compose does not appear to have a squash feature.  Only the docker build command has the squash flag.

We have discussed using `docker import` and `docker export` to simulate less layers

**Comment by infosec-alchemist** [comment]
This process did not work.
