### ISSUE TITLE
Error creating config file in api_configuration_tool

### ISSUE THREAD

**Issue by dRy3vd** [unfetter-discover/unfetter#1120]
When running the api_configuration_tool.py, an error is thrown when trying to write the private-config.ts file when the file does not exist.  The error occurs within method update_ui_env after the main else condition when the following line is executed: 

`env_file = open(ui_cfg_file, 'w')`

The reason this error occurs is due to the missing 'global' directory in ../unfetter-ui/src due to this line of code in the main method:

` ui_cfg_file = os.path.join(ui_path + '/src/global/private-config.ts')`

![image](https://user-images.githubusercontent.com/21263657/41066569-424b25b2-69b0-11e8-8fcf-3cad4ed63b11.png)

**Comment by webiator** [comment]
This is OBE. PR #491 changes this path to /src/assets.
