### ISSUE TITLE
Baselines: Summary Component -- Complete info bar functionality

### ISSUE THREAD

**Issue by mpmmasterpeace** [unfetter-discover/unfetter#1142]
Percentage of attack patterns weighted should appear in the dismissible info bar at top of page.
COMPLETE button should be added and take the user to edit current baseline when clicked.

Recommendations:
Look at assess-beta for how the info bar with percentage and COMPLETE button work.
Use the summary-calculation service to store the percentage complete so that the value can also be used for the middle chart in the main area of the component as in #1145

**Comment by sbertrandmitre** [comment]
Value of 2% complete is hardcoded - reopening to fix the problem.
