### ISSUE TITLE
Baselines: Summary Component -- Complete data for Baselines mega menu

### ISSUE THREAD

**Issue by mpmmasterpeace** [unfetter-discover/unfetter#1147]
Data on Baselines mega menu should match the actual data.

- Status should match the published / draft status (currently always draft)
- number of Capabilities should match actual # (currently always zero)
- ~~Check on Type (should match framework)~~
- ~~Check on Industry (unsure what this should match)~~

Recommendations:
- look at how # of capabilities is calculated in the Baseline Stats component
- look at how published / draft is detected in the result header

**Comment by sbertrandmitre** [comment]
We'll be removing Type and Industry for now, as there isn't any way to derive the former on a baseline-by-baseline basis and there is no attribute on the baseline for the latter.
