### ISSUE TITLE
Error switching to assessments beta page

### ISSUE THREAD

**Issue by webiator** [unfetter-discover/unfetter#1162]
When switching from one dashboard to the Assessments Beta page, this happens and the page doesn't load:
```
TypeError: _this.summaries[0].determineAssessmentType is not a function
```
Doesn't happen on refresh, or if you go straight to that page from the main page.

**Comment by mushinlogit** [comment]
I see this sometimes in latest chrome as well.  I think it is an intermittent loading time issue.

**Comment by mushinlogit** [comment]
still seeing this issue. it happens very rarely, but there is no user indication and only a console error.  I havent had time to track this down fully

**Comment by mushinlogit** [comment]
I added a selector to fetch the assessment name
```
+export const getFullAssessmentName = createSelector(
+    getFullAssessment,
+    (assessment: Assessment) => {
+        const assessmentType = (assessment !== undefined && assessment.determineAssessmentType) ?
+            assessment.determineAssessmentType() : 'Unknown';
+        return `${assessment.name} - ${assessmentType}`;
+    }
+);
```

**Comment by mushinlogit** [comment]
This error happened on both the summary and results tabs. we put in extra guards and I am not seeing this error for now.  We can reopen/create new issue if this bug is seen again
