### ISSUE TITLE
Permission denied errors during build on RHEL server

### ISSUE THREAD

**Issue by dRy3vd** [unfetter-discover/unfetter#1182]
I'm running into several permission errors during the build of unfetter when I try on my RHEL server.  I do **not** have the same issue on my mac.  Some suggestions for similar issues I found online point to this being related to SELinux enabled on the server, which I have confirmed it is not enabled.  Has anyone ran into this before or have suggestions?

Docker version 18.03.1-ce, build 9ee9f40
RHEL v7.5
Kernel: 3.10.0-693.21.1.el7.x86_64

Command to bring up unfetter:
`docker-compose -f docker-compose.yml -f docker-compose.deploy.yml up`

The permission errors I encounter are:
unfetter-pattern-handler       | PermissionError: [Errno 13] Permission denied: '/opt/stix/app.py'
unfetter-api-explorer          | sh: can't create ../unfetter-api-explorer/src/assets/swagger.json: Permission denied
unfetter-discover-api          | sh: can't create api/swagger/swagger.json: Permission denied
unfetter-ctf-ingest            | cp: can't stat 'src/api/swagger/swagger.yaml': Permission denied

Here is snippet output to show more detail:
unfetter-discover-api          |
unfetter-discover-api          | > unfetter-discover-api@0.3.7 startdeploy /usr/share/unfetter-discover-api
unfetter-discover-api          | > npm run compileswagger && pm2-docker start api/server/server.js -i max
unfetter-discover-api          |
unfetter-discover-api          |
unfetter-discover-api          | > unfetter-discover-api@0.3.7 compileswagger /usr/share/unfetter-discover-api
unfetter-discover-api          | > multi-file-swagger multifile.yaml > api/swagger/swagger.json && json2yaml ./api/swagger/swagger.json > ./api/swagger/swagger.yaml && swagger validate ./api/swagger/swagger.yaml
unfetter-discover-api          |
unfetter-discover-api          | sh: can't create api/swagger/swagger.json: Permission denied
unfetter-discover-api          | npm ERR! code ELIFECYCLE
unfetter-discover-api          | npm ERR! errno 1
unfetter-discover-api          | npm ERR! unfetter-discover-api@0.3.7 compileswagger: `multi-file-swagger multifile.yaml > api/swagger/swagger.json && json2yaml ./api/swagger/swagger.json > ./api/swagger/swagger.yaml && swagger validate ./api/swagger/swagger.yaml`
unfetter-discover-api          | npm ERR! Exit status 1
unfetter-discover-api          | npm ERR!
unfetter-discover-api          | npm ERR! Failed at the unfetter-discover-api@0.3.7 compileswagger script.
unfetter-discover-api          | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
unfetter-discover-api          |
unfetter-discover-api          | npm ERR! A complete log of this run can be found in:
unfetter-discover-api          | npm ERR!     /root/.npm/_logs/2018-06-21T18_25_17_834Z-debug.log
unfetter-discover-api          | npm ERR! code ELIFECYCLE
unfetter-discover-api          | npm ERR! errno 1
unfetter-discover-api          | npm ERR! unfetter-discover-api@0.3.7 startdeploy: `npm run compileswagger && pm2-docker start api/server/server.js -i max`
unfetter-discover-api          | npm ERR! Exit status 1
unfetter-discover-api          | npm ERR!
unfetter-discover-api          | npm ERR! Failed at the unfetter-discover-api@0.3.7 startdeploy script.
unfetter-discover-api          | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
unfetter-discover-api          |
unfetter-discover-api          | npm ERR! A complete log of this run can be found in:
unfetter-discover-api          | npm ERR!     /root/.npm/_logs/2018-06-21T18_25_17_904Z-debug.log

**Comment by infosec-alchemist** [comment]
recommend looking at the following:
- what is the user of the local files, and what permissions do they have
- start the container and look at the permission fo the files in docker.
- sounds like a mismatch with owner/permission of the files on your deployment machine, and the account running docker.

**Comment by dRy3vd** [comment]
More debugging and I found the source of the errors with a workaround.  Also, I confirmed this issue is not isolated to RHELs; I duplicated the issue on Ubuntu 16.04 LTS.

--For unfetter-discover-api--
The Dockerfile contains the following lines:
```
RUN touch $WORKING_DIRECTORY/api/swagger/swagger.json && chmod 666 $WORKING_DIRECTORY/api/swagger/swagger.json
RUN touch $WORKING_DIRECTORY/api/swagger/swagger.yaml && chmod 666 $WORKING_DIRECTORY/api/swagger/swagger.yaml
RUN touch $WORKING_DIRECTORY/api/swagger/swagger-remote.json && chmod 666 $WORKING_DIRECTORY/api/swagger/swagger-remote.json
RUN touch $WORKING_DIRECTORY/api/swagger/swagger-remote.yaml && chmod 666 $WORKING_DIRECTORY/api/swagger/swagger-remote.yaml
```
This is the cause of the permission issue.  The workaround is to manually create the empty swagger files with proper perms in ../api/swagger before bringing up the container and then removing the four lines mentioned above.  

--For unfetter-api-explorer--
The package.json file contains the line:
```
"compile:swagger": "cd ../unfetter-discover-api && multi-file-swagger multifile-remote.yaml > ../unfetter-api-explorer/src/assets/swagger.json && cd ../unfetter-api-explorer && cp ./src/assets/swagger.json ./src/explorer/assets/swagger.json && swagger validate ./src/assets/swagger.json",
    "start": "npm run build && http-server -p 3200 dist/",
    "start:dev": "npm run compile:swagger && webpack-dev-server",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "UNFETTER",
  "license": "MIT",
  "devDependencies": {
    "babel-core": "^6.26.0",
    "babel-loader": "^7.1.2",
    "babel-preset-es2015": "^6.24.1",
    "copy-webpack-plugin": "^4.3.1",
    "css-loader": "^0.28.9",
    "html-webpack-plugin": "^3.0.6",
    "json2yaml": "^1.1.0",
    "multi-file-swagger": "^2.2.0",
    "node-sass": "^4.7.2",
    "sass-loader": "^6.0.6",
    "style-loader": "^0.20.1",
    "swagger": "^0.7.5",
    "webpack": "^3.10.0",
    "webpack-dev-server": "^2.11.1"
  },
  "dependencies": {
    "axios": "^0.18.0",
    "swagger-ui-dist": "^3.9.3"
  }
}
```
multi-file-swagger is trying to create the file and it fails due to a permission issue; the workaround is to manually create these two file outside of the container by running multi-file-swagger multifile-remote.yaml > swagger.json and copy into the respective directories:
./src/assets/swagger.json ./src/explorer/assets/swagger.json

Why is the permission occurring? I'm not sure as the container was running as root but this workaround will get you going.

--For unfetter-pattern-handler--
This was a red herring; it was proxy issue with pip3 install located in the Dockerfile in stix2pattern.

Hope this helps!  However, I'm still not sure why the permissions issues exist.  To repo, do a fresh pull and try to build.

**Comment by infosec-alchemist** [comment]
there might be a problem with deploying in Ubuntu or Redhat.  We will have to investigate

**Comment by infosec-alchemist** [comment]
We have completely redone our deployment process with Ansible.  Hopefully this will help some of those problems.
