### ISSUE TITLE
Investigate carousel alternatives / remove primeng

### ISSUE THREAD

**Issue by j987987** [unfetter-discover/unfetter#1186]
Currently, three widgets from Primeng are being used in Unfetter: carousel, accordion, and data list. Primeng has jquery as a dependency, increases our bundle size thus load times, and is aesthetically inconsistent with our application.

There are Angular Material alternatives to the accordion and data list, but not a direct alternative to the carousel.

Some possibilities:
- Completely custom
- Custom controls with another library handling the 'slides', eg Angular Material tabs
- One of the various ng- compatible carousels on npm (note, many of these assume images will be the content and may not work for our purposes)
- A custom directive for a bootstrap caousel

**Comment by webiator** [comment]
OBE, #1387.
