### ISSUE TITLE
streamline the organization admin process

### ISSUE THREAD

**Issue by infosec-alchemist** [unfetter-discover/unfetter#1191]
- [x] Allow admins to accept a new user and assign them to an organization
- [x] When a user logs in for the first time, if they don't have an org assigned, they get an alert to sign for one
- [ ] Change the "Unfetter Open" to "general" to make it more generic/

**Comment by j987987** [comment]
Going to make a PR without the 3rd step.  We've discussed removing Unfetter open, which would require more refactoring and testing.
