### ISSUE TITLE
Error with User promotion tool

### ISSUE THREAD

**Issue by infosec-alchemist** [unfetter-discover/unfetter#1197]
When running the user promotion python program "user_promosion_tool.py", I get the following error

```
{u'organizations': [], u'github': {u'userName': u'infosec-alchemist', u'avatar_url': u'https://avatars2.githubusercontent.com/u/19472140?v=4', u'id': u'19472140'}, u'locked': False, u'preferences': {u'killchain': u'mitre-attack'}, u'created': datetime.datetime(2018, 6, 26, 17, 38, 32, 758000), u'registered': False, u'__v': 0, u'role': u'STANDARD_USER', u'oauth': u'github', u'_id': ObjectId('5b327a18cf15b100435c2b41'), u'approved': False, u'identity': {u'identity_class': u'individual', u'type': u'identity', u'modified': datetime.datetime(2018, 6, 26, 17, 38, 32, 758000), u'sectors': [], u'created': datetime.datetime(2018, 6, 26, 17, 38, 32, 758000)}}

***************

Registered Users:

        Index - User Name - User Role
Traceback (most recent call last):
  File "user_promotion_tool.py", line 26, in <module>
    print '\t' + str(i) + ' -- ' + users[i][u'userName'] + ' -- ' + users[i][u'role']
```

**Comment by infosec-alchemist** [comment]
The error is caused because the returned user collection has username as part of a github or gitlab object in the returned json.

**Comment by infosec-alchemist** [comment]
Put in a check to see if 'gitlab' or 'github' key exists in each user before printing the user name

**Comment by webiator** [comment]
I don't understand why this would be the cause of the error. The Unfetter user object has a userName property, and it would make sense that we would only want to present one line per user, regardless of how many external accounts we have associated with them. Is this actually a Python problem? (I can't see why it would be.)

**Comment by webiator** [comment]
For grins, I edited one of my local user accounts that was using GitHub, and added another auth entry for Gitlab. The user_promotion_tool had no issues presenting the user list. I will try to dig into your output above to see what else might have been the source of the error.

**Comment by webiator** [comment]
registered: False

This is why the user_promotion_tool failed. After you login for the first time with a service, the UI will present a registration page. On that page you get to enter your own Unfetter userName, email address, etc. You bypassed this step and went straight to the user_promotion_tool, which was complaining that it could not find your Unfetter userName property.

Even with the PR you created, there still would not be a userName attached to the user database entry, so I would imagine there would still be weird UI artifacts. Such as clicking on your icon, the dropdown would not show your userName.
