### ISSUE TITLE
Allow uploading of a document file attached to analytics

### ISSUE THREAD

**Issue by infosec-alchemist** [unfetter-discover/unfetter#1207]
When an analytic is described, allow one or more documents to be uploaded, with the ability to download.  

- [x] Allow one or more uploads of a file
- [x] Allow downloads of those files
- [ ] allow the admin to turn off file upload/download globally

**Comment by j987987** [comment]
The scope of the first PR for this will be steps 1 and 2.

**Comment by infosec-alchemist** [comment]
I am happy if you split the Issue up so you can match issue to the PR.

**Comment by j987987** [comment]
I added the last step to #1278 , closing this one.
