### ISSUE TITLE
gitlab and github UAC fails when site is not hosted on localhost

### ISSUE THREAD

**Issue by dRy3vd** [unfetter-discover/unfetter#1232]
gitlab-auth.js and github-auth.js respectively contain the following lines:
`callbackURL: `${(env.API_ROOT || 'https://localhost/api')}/auth/gitlab-callback``
and
`callbackURL: `${(env.API_ROOT || 'https://localhost/api')}/auth/github-callback``

env.API_ROOT is not defined anywhere thus it fails if not deployed on localhost.

Fix: define env variable referencing the hosted locatation in the docker-compose.deploy.yml or docker-compose.development.yml for the unfetter-discover-api container.  For example:

```
    environment:
    # Options: UAC, TEST, DEMO
    - RUN_MODE=UAC
    # If deployed in a proxy, add the proxy's URL here
    # Define host in API_ROOT needed for the API
    - API_ROOT=https://<host name or IP address>/api
```

**Comment by j987987** [comment]
Thanks for the feedback, dRy3vd.

With this fix, rerunning the `api_configuration_tool.py` script should resolve the problem, as it will prompt the user for the API's domain to generate the API root.
