### ISSUE TITLE
docker-compose down creates oprhaned containers

### ISSUE THREAD

**Issue by dRy3vd** [unfetter-discover/unfetter#1233]
ryan@thebox:~/unfetter-discover/unfetter$ docker-compose down
Stopping unfetter-discover-gateway ... done
Stopping unfetter-ctf-ingest       ... done
Stopping unfetter-discover-api     ... done
Stopping unfetter-api-explorer     ... done
Stopping cti-stix-store-repository ... done
Stopping unfetter-pattern-handler  ... done
WARNING: Found orphan containers (unfetter-socket-server) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
Removing unfetter-discover-gateway   ... done
Removing unfetter-ctf-ingest         ... done
Removing unfetter-discover-api       ... done
Removing unfetter-discover-processor ... done
Removing unfetter-api-explorer       ... done
Removing cti-stix-store-repository   ... done
Removing unfetter-pattern-handler    ... done
Removing unfetter-discover-openssl   ... done
Removing network unfetter_default
ERROR: network unfetter_default id 6f627365f1fc6f620ac3137044909284372f015653d1669ddb7cbb8745383035 has active endpoints
ryan@thebox:~/unfetter-discover/unfetter$ docker-compose down --remove-orphans
Removing orphan container "unfetter-socket-server"
Removing network unfetter_default

Workaround: docker-compose down --remove-orphans
if this fails to allow containers to be brought up successfully next time (sometimes unfetter-ui will error out), run the following command: docker system prune.  This should allow unfetter to be brought up without errors on the next try.

**Comment by infosec-alchemist** [comment]
Thanks.  However, normally operation will not have actual orphaned container for socket-server.  This is likely because the socket-server crashed.
