### ISSUE TITLE
Problem with visibility for Work Products on Threat Dashboard

### ISSUE THREAD

**Issue by mpmmasterpeace** [unfetter-discover/unfetter#1245]
Default work products are visible by anyone in an organization.
However, if a user edits one it is only visible to that user.
Newly created work products are also only visible to the creator.

Hypothesis: The published flag is set to true on the demo work products but changes to false (draft) on edit. Since there is no way to "publish" a work product, any created or edited product is only visible to the creator/editor.

**Comment by mpmmasterpeace** [comment]
Fixed by https://github.com/unfetter-discover/unfetter-ui/pull/561

**Comment by mushinlogit** [comment]
@mpmmasterpeace I was not able to reproduce this issue.  The published flag on a work product was not being set to false/true on save/edit.  Also a workproduct meta property object does not have a created_by_ref to be manipulated by the security filter.  
However, maybe a report could be saved/edited and that might cause issue? I created a PR to remove bad created_by_ref values in the test data, and will continue testing.  See referenced PRs

**Comment by mushinlogit** [comment]
I changed the imported reports to use the unfetter open group, so they correctly with the security filter.

A workproduct's security is an aggregate of its containing reports.  This might not be ideal, but workproducts were modeled before the security filter and published flags were conceptualized.  

I was not able to reproduce this issue, will close and reopen if we have a better test case
