### ISSUE TITLE
Baselines: wizard should navigate to first incomplete capability on edit

### ISSUE THREAD

**Issue by sbertrandmitre** [unfetter-discover/unfetter#1260]
When choosing to edit a baseline, the wizard should navigate automatically to the first capability in the baseline which is not completely scored.

**Comment by joe-dam** [comment]
How about an alert when navigating away from the current capability that not all scores are weighted? Editing would then still take you to the beginning, though when going through and clicking continue, you will prompted with a message such as: Not all attack patterns have been scored. Are you sure you want to continue?
