### ISSUE TITLE
Replace AP selector in baselines with one used in Analytic Exchange

### ISSUE THREAD

**Issue by sbertrandmitre** [unfetter-discover/unfetter#1272]
There are slight differences in appearance between the AP selector in baselines and the AP selector configured in the Analytic Exchange.  Differences should be highlighted, and the AP selector in Baselines should be made to perform and look like the one in the Analytic Exchange.

**Comment by webiator** [comment]
The only differences I see are colors (which is theme-based), the presence of a Clear button (which I agree would be nice to add to AE), and the placement of the buttons (upper right vice lower left). See images below. Is there something I am missing? This is with the Mitre framework, maybe other frameworks have some UI issues?

AE:
![screen shot 2018-07-19 at 3 19 04 pm](https://user-images.githubusercontent.com/6414732/42965277-7eb9e6a4-8b67-11e8-9463-5efe34c59393.png)

Baselines:
![screen shot 2018-07-19 at 3 19 20 pm](https://user-images.githubusercontent.com/6414732/42965283-84fc4642-8b67-11e8-9bb1-2abead2dba86.png)

**Comment by sbertrandmitre** [comment]
We'll make the button placement for the baselines wizard AP selector the same as that of the AE AP selector.  All other differences are specific to the respective screens.

**Comment by sbertrandmitre** [comment]
Will also add Clear button to AE AP selector.
