### ISSUE TITLE
Attachment enhancements

### ISSUE THREAD

**Issue by j987987** [unfetter-discover/unfetter#1278]
Possible enhancements to #1207 

- Make a custom file input element that allows for renaming and deleting of files from the file list
- Store data in a gzip format
- Ability to add/delete files while editing the analytic

Remaining step from #1207:

- Allow the admin to turn off file upload/download globally

**Comment by j987987** [comment]
Gzip notes:

```
// Storing in gziped format
const zlib = require('zlib');
const gzip = zlib.createGzip();

// .......
    file.stream
        .pipe(gzip)
// .......
```

```
// In response, set this header and browser will unzip it
res.setHeader('Content-Encoding', 'gzip');
```

**Comment by infosec-alchemist** [comment]
Can you validate that you CAN NOT reach the files via the URL?

**Comment by j987987** [comment]
#1207 focused on the backend requirements, one of those being UAC considerations.

Accessing a file via URL requires two things:
- A valid JWT token in the query string of the URL
- Permission to view the STIX it was attached to

Otherwise, you'll get an error response.
