### ISSUE TITLE
Baseline saved with no groups or capabilities cannot be displayed in summary view

### ISSUE THREAD

**Issue by sbertrandmitre** [unfetter-discover/unfetter#1280]
Create a new baseline.
At capability group screen in wizard, click Continue.
Click Save at wizard summary.
`"Error 404 - The request URL was not found in the application."`

**Comment by sbertrandmitre** [comment]
Note:  a GET with the assessment set ID of the baseline succeeds in the API explorer.  Must be a problem with some piece of code expecting there to be 1 or more object assessments.

**Comment by sbertrandmitre** [comment]
This error also occurs when there are capability groups but no capabilities selected.

**Comment by joe-dam** [comment]
Can this be fixed by disabling the continue button until at least 1 group or capability is selected?
