### ISSUE TITLE
Evauluate the STIX data in the ATTACK and NTCTF frameworks and combine

### ISSUE THREAD

**Issue by infosec-alchemist** [unfetter-discover/unfetter#1282]
We want as many of the attack-patterns to overlap between the NTCTF and MITRE Attack in actual attack-pattern data object

If there is an ATTACK attack-pattern that matches the intention of an NTCTF attack-pattern, the remove the NTCTF attack pattern and ensure that the STIX data adds a new external reference and kill chain phase pointing to the NTCTF

**Comment by sbertrandmitre** [comment]
Closing this per PR #1493
