### ISSUE TITLE
Deleting Last Capability Group from a Previously Saved Baseline doesn't Stick

### ISSUE THREAD

**Issue by mpmmasterpeace** [unfetter-discover/unfetter#1286]
### PROBLEM

After saving with 1 capability group and 1 capability, edit and remove the only capability group. Go to Summary step and save. Summary page shows 1 capability, and going back to edit shows the removed capability group present

### FIX

Make sure removal of a capability group (and a capability) are persisted when Save button is pressed (or any "auto save" time).

**Comment by joe-dam** [comment]
Do we want any kind of warning message when a group is being deleted? Removing this group will remove # capabilities from this baseline assessment.

**Comment by mpmmasterpeace** [comment]
I don't think that's necessary. We can revisit later if it feels too easy to make mistakes.
