### ISSUE TITLE
Registration automatically assigns user to org

### ISSUE THREAD

**Issue by webiator** [unfetter-discover/unfetter#1287]
If this is intentional, please just close the ticket.

~~- [ ] When a user registers, they are asked which org they would like to join. This is a freeform field, and is not mapped to an actual, existing org.~~

- [ ] On the admin screen, the `Join Orgs` dropdown does not list `Unfetter Open`. The user document already has it added, even though they are not yet approved. If this is "standard", then just disregard this issue. ~~Would also recommend the dropdown highlight the user's requested org.~~

**Comment by infosec-alchemist** [comment]
We have the 'which org" to be free form because we dont' want unknown users knowing which organizations are already loaded into Unfetter.  For public deployments, this could give away information.

**Comment by webiator** [comment]
@infosec-alchemist, is "Unfetter Open" a standard org we want all users added to automatically as well?

**Comment by infosec-alchemist** [comment]
Yes, that is an automatically added Org.  It is for all the Unfetter provided data.
