### ISSUE TITLE
Back-to-summary arrow not present on wizard for new baselines

### ISSUE THREAD

**Issue by sbertrandmitre** [unfetter-discover/unfetter#1288]

**Comment by joe-dam** [comment]
Not sure what you mean by this? Can't you click cancel to return to summary?

**Comment by sbertrandmitre** [comment]
Consider screenshots from assessments beta and baselines - no arrow to left of baseline name.  This arrow is the only way to essentially exit out of the `new baseline` process.  Auto save is in place for baselines - and is not for assessments beta - but the user should still have the ability to go back to the summary screen.
![screen shot 2018-07-25 at 10 50 29 am](https://user-images.githubusercontent.com/34275439/43208776-29c3ae3c-8ff9-11e8-8cd1-d16df4436aa7.png)
![screen shot 2018-07-25 at 10 50 00 am](https://user-images.githubusercontent.com/34275439/43208783-2dbc4da0-8ff9-11e8-9b80-599e0dafc942.png)
