### ISSUE TITLE
unfetter-discover-processor exited with code 0

### ISSUE THREAD

**Issue by threatinteltest** [unfetter-discover/unfetter#129]
Steps to reproduce: 

Performing either of the published cases to download and launch unfetter leads to the same failure to launch issues.

Expected results: functioning sites to work on.

Actual results: 

cti-stix-store-repository exited with code 100
unfetter-discover-openssl exited with code 0
cti-stix-store                 | (node:17) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 connected listeners added. Use emitter.setMaxListeners() to increase limit
cti-stix-store                 | (node:17) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
unfetter-discover-processor exited with code 0

Going to the following locations yield a payload 502 error.  
	Reports
	Intrusion set dashboard
	Any links under settings
	
Can launch the cti-stix-ui but any link on there also returns the payload 502 error.

Environment:
	OSX 10.10.5 
	Docker 17.03.1-ce-mac5(16048) Stable

**Comment by dev-jitsu** [comment]
I'm working through and trying to reproduce the errors you're seeing.  The unfetter-discover-openssl exit code 0 is normal.  I don't see the cti-stix-store-repository exit code 100 when I run the "Case 1" scenario.  I haven't tried "Case 2" yet.  We had been experiencing a race condition where the store tried to write to the repository before the container was ready but that doesn't seem to be the problem you're having.  Can you try docker-compose up multiple times and see if you get the same errors?

**Comment by threatinteltest** [comment]
After several restarts with he docker-compose up. I get this consistent error message before the 

Connection fails: MongoError: failed to connect to server [repository:27017] on first connect
cti-stix-store                 | It will be retried for the next request.
cti-stix-store                 | 
cti-stix-store                 | /usr/share/cti-stix-store/node_modules/mongodb/lib/mongo_client.js:336
cti-stix-store                 |           throw err
cti-stix-store                 |           ^
cti-stix-store                 | MongoError: failed to connect to server [repository:27017] on first connect
cti-stix-store                 |     at Pool.<anonymous> (/usr/share/cti-stix-store/node_modules/mongodb-core/lib/topologies/server.js:326:35)
cti-stix-store                 |     at emitOne (events.js:96:13)
cti-stix-store                 |     at Pool.emit (events.js:191:7)
cti-stix-store                 |     at Connection.<anonymous> (/usr/share/cti-stix-store/node_modules/mongodb-core/lib/connection/pool.js:270:12)
cti-stix-store                 |     at Object.onceWrapper (events.js:293:19)
cti-stix-store                 |     at emitTwo (events.js:106:13)
cti-stix-store                 |     at Connection.emit (events.js:194:7)
cti-stix-store                 |     at Socket.<anonymous> (/usr/share/cti-stix-store/node_modules/mongodb-core/lib/connection/connection.js:185:10)
cti-stix-store                 |     at Object.onceWrapper (events.js:293:19)
cti-stix-store                 |     at emitNone (events.js:86:13)
cti-stix-store                 |     at Socket.emit (events.js:188:7)
cti-stix-store                 |     at Socket._onTimeout (net.js:345:8)
cti-stix-store                 |     at ontimeout (timers.js:380:14)
cti-stix-store                 |     at tryOnTimeout (timers.js:244:5)
cti-stix-store                 |     at Timer.listOnTimeout (timers.js:214:5)
cti-stix-store                 | 
cti-stix-store                 | npm ERR! Linux 4.9.13-moby
cti-stix-store                 | npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
cti-stix-store                 | npm ERR! node v7.7.1
cti-stix-store                 | npm ERR! npm  v4.3.0
cti-stix-store                 | npm ERR! code ELIFECYCLE
cti-stix-store                 | npm ERR! errno 1
cti-stix-store                 | npm ERR! cti-stix-store@0.2.5 start: `node .`
cti-stix-store                 | npm ERR! Exit status 1
cti-stix-store                 | npm ERR! 
cti-stix-store                 | npm ERR! Failed at the cti-stix-store@0.2.5 start script 'node .'.
cti-stix-store                 | npm ERR! Make sure you have the latest version of node.js and npm installed.
cti-stix-store                 | npm ERR! If you do, this is most likely a problem with the cti-stix-store package,
cti-stix-store                 | npm ERR! not with npm itself.
cti-stix-store                 | npm ERR! Tell the author that this fails on your system:
cti-stix-store                 | npm ERR!     node .
cti-stix-store                 | npm ERR! You can get information on how to open an issue for this project with:
cti-stix-store                 | npm ERR!     npm bugs cti-stix-store
cti-stix-store                 | npm ERR! Or if that isn't available, you can get their info via:
cti-stix-store                 | npm ERR!     npm owner ls cti-stix-store
cti-stix-store                 | npm ERR! There is likely additional logging output above.
cti-stix-store                 | 
cti-stix-store                 | npm ERR! Please include the following file with any support request:
cti-stix-store                 | npm ERR!     /root/.npm/_logs/2017-04-03T18_50_34_655Z-debug.log
cti-stix-ui                    | 
cti-stix-ui                    | components/select-search-field-external.js: line 36, col 43, Missing semicolon.
cti-stix-ui                    | 
cti-stix-ui                    | 1 error
cti-stix-ui                    | 
cti-stix-ui                    | controllers/intrusion-set-edit.js: line 168, col 17, 'self' is defined but never used.
cti-stix-ui                    | controllers/intrusion-set-edit.js: line 167, col 14, 'item' is defined but never used.
cti-stix-ui                    | 
cti-stix-ui                    | 2 errors
cti-stix-ui                    | 
cti-stix-ui                    | ===== 2 JSHint Errors
cti-stix-ui                    | 
cti-stix-store exited with code 1

**Comment by dev-jitsu** [comment]
Ok thanks.  That's the race condition we've been seeing.  We'll have the fix published to the master branch tomorrow.  Still not sure about the memory leak error you had on first run but hopefully it won't be an issue after the update.  I'll let you know when it's available.

**Comment by threatinteltest** [comment]
Thanks for the update!

**Comment by dev-jitsu** [comment]
Ok, let's try again.  If you try the Case 1 scenario you'll just need to get into the unfetter folder and do a "git pull".  Then delete any unfetter Docker containers and images then run the "docker-compose up" again.  Thanks for you patience, let me know how it goes.

**Comment by threatinteltest** [comment]
Tried it again both ways. Even started on a clean system, both approaches left the same error message.  


cti-stix-ui                    | components/select-search-field-external.js: line 36, col 43, Missing semicolon.
cti-stix-ui                    | 
cti-stix-ui                    | 1 error
cti-stix-ui                    | 
cti-stix-ui                    | controllers/intrusion-set-edit.js: line 168, col 17, 'self' is defined but never used.
cti-stix-ui                    | controllers/intrusion-set-edit.js: line 167, col 14, 'item' is defined but never used.
cti-stix-ui                    | 
cti-stix-ui                    | 2 errors
cti-stix-ui                    | 
cti-stix-ui                    | ===== 2 JSHint Errors
cti-stix-ui                    | 
unfetter-discover-ui           | 
unfetter-discover-ui           | Build successful - 23886ms.
unfetter-discover-ui           | 
unfetter-discover-ui           | Slowest Trees                                 | Total               
unfetter-discover-ui           | ----------------------------------------------+---------------------
unfetter-discover-ui           | broccoli-persistent-filter:Babel              | 7080ms              
unfetter-discover-ui           | broccoli-persistent-filter:Babel > [Babel:... | 4913ms              
unfetter-discover-ui           | broccoli-persistent-filter:Babel > [Babel:... | 2279ms              
unfetter-discover-ui           | 
unfetter-discover-ui           | Slowest Trees (cumulative)                    | Total (avg)         
unfetter-discover-ui           | ----------------------------------------------+---------------------
unfetter-discover-ui           | broccoli-persistent-filter:Babel (5)          | 7965ms (1593 ms)    
unfetter-discover-ui           | broccoli-persistent-filter:Babel > [Ba... (2) | 5098ms (2549 ms)    
unfetter-discover-ui           | broccoli-persistent-filter:Babel > [Ba... (1) | 2279ms              
unfetter-discover-ui           | AMDDefineFilter (30)                          | 2173ms (72 ms)      
unfetter-discover-ui           | 
cti-stix-ui                    | 
cti-stix-ui                    | Build successful - 25351ms.
cti-stix-ui                    | 
cti-stix-ui                    | Slowest Trees                                 | Total               
cti-stix-ui                    | ----------------------------------------------+---------------------
cti-stix-ui                    | broccoli-persistent-filter:Babel > [Babel:... | 8206ms              
cti-stix-ui                    | broccoli-persistent-filter:Babel              | 6720ms              
cti-stix-ui                    | broccoli-persistent-filter:Babel > [Babel:... | 2160ms              
cti-stix-ui                    | 
cti-stix-ui                    | Slowest Trees (cumulative)                    | Total (avg)         
cti-stix-ui                    | ----------------------------------------------+---------------------
cti-stix-ui                    | broccoli-persistent-filter:Babel > [Ba... (2) | 8388ms (4194 ms)    
cti-stix-ui                    | broccoli-persistent-filter:Babel (5)          | 7984ms (1596 ms)    
cti-stix-ui                    | broccoli-persistent-filter:Babel > [Ba... (1) | 2160ms              
cti-stix-ui                    | 
unfetter-discover-processor    | events.js:163
unfetter-discover-processor    |       throw er; // Unhandled 'error' event
unfetter-discover-processor    |       ^
unfetter-discover-processor    | 
unfetter-discover-processor    | Error: connect ECONNREFUSED 198.105.254.23:3000
unfetter-discover-processor    |     at Object.exports._errnoException (util.js:1029:11)
unfetter-discover-processor    |     at exports._exceptionWithHostPort (util.js:1052:20)
unfetter-discover-processor    |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1093:14)
unfetter-discover-processor exited with code 1

**Comment by dev-jitsu** [comment]
Ok, I see.  There's still a race condition.  I'm making changes and testing now.  I can't reproduce it on my dev machine so it's taking some time to debug.  I'll keep you posted again soon.

**Comment by dev-jitsu** [comment]
I've been able to get it running outside of my dev machine (Macbook) on Centos and Windows 10 so hopefully this is the right set of changes.  Try killing all the containers and the "unfetter/unfetter-discover-processor" image.  docker-compose up will pull the new one from Docker hub and you should be good to go.

**Comment by threatinteltest** [comment]
This time I tried on OS X, Suse, Ubuntu and Win10 64 bit. I am able to get the images to come up, but on each of them I run into the same Payload 502 error on the pages.

**Comment by infosec-alchemist** [comment]
Hi, we are having trouble replicating the problem.  If you are behind a work proxy, that might be causing some problems.

Could you rerun the docker-compose up with the verbose flag, and put the entire output in gist?

docker-compose --verbose up > output.txt

**Comment by threatinteltest** [comment]
I am going to close this issue. After thinking about what you said with the proxy I figured out that when I deleted containers I had two that would not delete. I ended up using docker-clean to remove them and now it is working. Thank you for the help!

**Comment by infosec-alchemist** [comment]
Glad you got this worked out.  I've found some weird things with Docker not completely deleting everything you think it should.  Although, we used to work with Vagrant and that was even worse.  Let us know if you have any more problems.
