### ISSUE TITLE
Minor Visual Enhancement for Capability Weighting in Baseline Creation

### ISSUE THREAD

**Issue by mpmmasterpeace** [unfetter-discover/unfetter#1302]
### Problem

Left Nav has too much space between a sub item and the next item (a capability and Summary item for example)

### Fix

Tighten up spacing using CSS. Next Capability Group or Summary heading should be the same distance from a Capability item as between any top level heading. See image.
![screen shot 2018-07-25 at 7 11 17 am](https://user-images.githubusercontent.com/24652622/43197892-aecda606-8fda-11e8-9604-e2dc2679ea7a.png)

**Comment by sbertrandmitre** [comment]
In all honesty, I tried fixing this when I first implemented it and had a hard time.  Any suggestions are welcome!

**Comment by mpmmasterpeace** [comment]
I believe adding the below code to wizard.component.scss, nested in .sidenav, .mat-expansion-panel get most of the way there. Just need to correct the little movement hiccup when selecting one of the headings (opens bigger then corrects).

`::ng-deep .mat-expanded {`
`     .mat-expansion-panel-body {`
`           padding: 0px 24px 0px 24px;`
`      }`
`}`
