### ISSUE TITLE
Remove Beta from Baselines

### ISSUE THREAD

**Issue by mpmmasterpeace** [unfetter-discover/unfetter#1306]
### PROBLEM

Baselines is moving out of beta and should reflect that in iconography and infobar.

### FIXES

- [ ] Remove Beta icon and utilize new Baselines icon (if we do not have, check with ADG Creative)

- [ ] Remove beta text from Baselines infobar, but leave percent complete.

**Comment by sbertrandmitre** [comment]
No baselines icon in latest icon set - have posted to design channel to check with ADG...
