### ISSUE TITLE
threat dashboard: autocomplete markdown feature

### ISSUE THREAD

**Issue by mushinlogit** [unfetter-discover/unfetter#1309]
related to: https://github.com/unfetter-discover/unfetter/issues/1226

The threat report allows for a custom markdown element to add intrusions and malware to the threat report meta data.  Allow for the ability to auto complete custom markdown triggers and values as the user types.  

should be able to hook into the selection callback

```typescipt
// (select)="selectionchange($event)"
selectionchange(ev: Event) {
  const start = ev.target.selectionStart;
  const end = ev.target.selectionEnd;
  console.log(ev.target.value.substr(start, end - start))
}
```

also consider;
```
For future consideration:

    Removing markup should remove associated chips
    Manually adding/removing chips should update markup
```

**Comment by mpmmasterpeace** [comment]
May be OBE with new threat dashboard design. Original work is complete, but not future considerations.

**Comment by j987987** [comment]
This work is functionally capture in this issue: https://github.com/unfetter-discover/unfetter/issues/1425
