### ISSUE TITLE
Silent fail on Baseline create if you don't provide an org

### ISSUE THREAD

**Issue by webiator** [unfetter-discover/unfetter#1319]
What to do:
- Create a Baseline
- Note that neither title nor description are marked required, but organization is. Continue button is disabled.
- Enter a title. Note the Continue button is now enabled (despite no organization being entered).
- Hit Continue. Nothing happens. (You will see an error in the developer console.)
- Select an org, then hit Continue. Nothing happens (Including in the console).
- Go back to Baselines, and hit Create again.
- Enter both a title and an org, hit Continue. Still nothing happens.

You have to fully refresh the page in order to enter both a title and org, and hit Continue.

**Comment by joe-dam** [comment]
I agree Title should have a * to indicate that it is required, but how are you getting no organization being entered?  I see a default value of Unfetter Open. Clicking the drop down does not have any other options.

**Comment by webiator** [comment]
Maybe your account only has one org assigned to it? I have two, with neither one being automatically selected. If I only have one, yes, the org is filled in automatically.
