### ISSUE TITLE
Mongo port needs to be open to run user promotion script

### ISSUE THREAD

**Issue by webiator** [unfetter-discover/unfetter#1342]
This is nothing new, but our `docker-compose.yml` file does not open this port (it is commented out). The `docker-compose.development.yml` file does open it. Regardless, the user-promotion script can only be run if that port is open, so establishing the initial admin user would require it. We either need:
- an alternative method of creating an admin user; or,
- this port would need to be open on all deployment strategies; or,
- since we are moved to ansible, add an ansible playbook that can somehow access mongo and run the script (or similar)

**Comment by infosec-alchemist** [comment]
There are two models.

There is an ansible script that will upgrade a single user, given their username.

In the unfetter-store, there is a script that builds a docker container which has access to the database, and runs the query.
