### ISSUE TITLE
task-push-registry playbook incomplete

### ISSUE THREAD

**Issue by webiator** [unfetter-discover/unfetter#1354]
- [x] Playbook does not create version/`latest` tags for unfetter-socket-server, does not push to docker hub.

- [x] Playbook creates `latest` tags for all other images, but does not push those tags to docker hub (intentional?).

- [x] Add a version tag for unfetter-discover-gateway (without .demo or .uac etc. suffixes) that points to the .demo tag, and push to docker hub. This allows the docker-compose.yml script to work without specifying the .demo suffix.

**Comment by infosec-alchemist** [comment]
- [ ] Change the order of tagging Unfetter-Discover-Gateway to make the code easier.  Instead of 
``` unfetter-discover-gateway:[version].[build type]``` we will switch the [version] and [build type]
- [ ] Force the registry to be a passed in value.  This will allow us to test
- [ ]
