### ISSUE TITLE
Allow Tagging of Unfetter Users in Threat Articles & Comments

### ISSUE THREAD

**Issue by mpmmasterpeace** [unfetter-discover/unfetter#1363]
### Task
Use @ or some other markup to allow tagging of other users in the system

### Implementation
Need mark-up generation
May want auto complete of users
Consider github's issue entry solution
Allow anywhere in a Threat Board

**Comment by j987987** [comment]
This was accomplished during: https://github.com/unfetter-discover/unfetter/issues/1424
