### ISSUE TITLE
Highlight Text from Threat Reports

### ISSUE THREAD

**Issue by mpmmasterpeace** [unfetter-discover/unfetter#1364]
### Task
Allow highlighting of text from a threat report

### Implementation
Utilize in the Article View
Highlighting should be occur in threat report when already inserted and saved in a threat article.

### Consider
Will want to be able to 'tag' highlighted text with Intrusion Sets, Attack Patterns, Mitigations

**Comment by j987987** [comment]
This work is captured in this issue https://github.com/unfetter-discover/unfetter/issues/1426
