### ISSUE TITLE
Improve handling of Ansible ports

### ISSUE THREAD

**Issue by j987987** [unfetter-discover/unfetter#1374]
The deprecated `unfetter/docker-compose.development.yml` file had port mappings for helping debug single services when in development mode.

- ingest: "3001:10010"
- socket: "13333:3333", "6555:6555"
- api: "49360:3000", "5555:5555"
- mongo: "27018:27017"
- pattern-handler: "5000:5000"

Currently, the ports for mongo and pattern handler are open in __all__ modes, where as the other port mappings are open in none.  Ideally, the above port mappings should be present when bringing up the stack with `deploy-dev.yml`, but not the other playbooks.

**Comment by webiator** [comment]
Doesn't the Mongo port need to be open in all modes just so the user_promotion_tool works (at least for the very first admin). I know I had to open it for my EC2 tests. I don't necessarily like it; if there's a way to rewrite the user_promotion_tool as an ansible playbook that can access Mongo, I'd be all for it.

**Comment by j987987** [comment]
@webiator - I'm making an intermediate solution of Dockerizing the promotion script - Ideally, there should be an ansible solution eventually.  Since it's a command line based app, the docker solution is not ideal.

**Comment by j987987** [comment]
I have created an intermediate solution here: https://github.com/unfetter-discover/unfetter-store/pull/246
