### ISSUE TITLE
Error when creating new assessment without a baseline

### ISSUE THREAD

**Issue by infosec-alchemist** [unfetter-discover/unfetter#1423]
When creating a new assessment, you are able to NOT SELECT a baseline.  When that happens, you go to an assessment page that has not options

![image](https://user-images.githubusercontent.com/19472140/45308924-9208c880-b4f0-11e8-8719-1081e19d5707.png)
![image](https://user-images.githubusercontent.com/19472140/45308935-99c86d00-b4f0-11e8-80ce-19151cf27473.png)

**Comment by sbertrandmitre** [comment]
For that matter, an assessment can be created without selecting any of indicators, mitigations, and baselines.  I would expect at least one of indicators, mitigations, and capabilities (and associated selected baseline) to be required to continue into the assessment.
