### ISSUE TITLE
Accidental submits on registration page

### ISSUE THREAD

**Issue by webiator** [unfetter-discover/unfetter#1432]
When you are first logging in to Unfetter, you are presented with a registration page. If you accidentally hit the Enter button while filling out the registration form, the form is submitted as is (even if the form is invalid). You will be kicked to the home page with the banner message "Thanks for registering...". Since the form was invalid, however, you will not actually be registered at all (you will have the normal pre-registration entry in the database). And because of that, administrators will not know about you (you will not be listed in the pending-approvals admin tab).

Either:
a) Pre-validate the form before submission (whatever the Angular equivalent to a form onSubmit handler would be), and keep the user on the page if validation fails (**preferred**); or,
b) When registering the user, if the form is invalid, return them to the registration page with errors.

**Comment by j987987** [comment]
I found another edge case while looking at this issue.  If the user's token expires when on the `/users/register` route and they reload the browser, it will just be a blank page.
