### ISSUE TITLE
task-prep-remote-host doesn't recognize user added to docker group

### ISSUE THREAD

**Issue by infosec-alchemist** [unfetter-discover/unfetter#1497]
When running task-prep-remote-host, the user is added to the Docker group.

However, there is an error when creating the Docker network.  Thats because the user, although added to the group, needs to refresh. 

Rerunning the playbook does not solve the problem.

A separate ssh connection made will refresh the groups, and allows the next run of the playbook to work.

In the playbook, somehow run a command that refreshes the user group.

**Comment by webiator** [comment]
Rerunning the playbook does solve it, it's just that sometimes, for some odd reason, it takes a few minutes to "kick in." Maybe it somehow reuses the ssh connection if you rerun it right away?

Possibly:
```
exec newgrp docker
exec newgrp -
```
- `exec` will replace the currently running shell with a new shell
- `newgrp docker` should add docker to the user's current group list (and make it the primary one)
- `newgrp -` should restore the user's primary group

Based on https://superuser.com/questions/272061/reload-a-linux-users-group-assignments-without-logging-out

**Comment by infosec-alchemist** [comment]
There is an ansible command that is supposed to reset the connection, but its broken in the version of Ansible I was running (2.5).  I am going to test out upgrading to 2.7 and see if its better.

I read that another fix is to put a 1 minute pause in there.  But thats super annoying
