### ISSUE TITLE
Can't create a threat board in DEMO

### ISSUE THREAD

**Issue by infosec-alchemist** [unfetter-discover/unfetter#1550]
In DEMO mode, i can not create a threat board.  I can click the "save", but nothing happens

![image](https://user-images.githubusercontent.com/19472140/48082457-b1566600-e1c0-11e8-8de2-41db951047ea.png)

**Comment by mpmmasterpeace** [comment]
Additional info:
error:
code: "SCHEMA_VALIDATION_FAILED"
failedValidation: true
message: "Request validation failed: Parameter (data) failed schema validation"
paramName: "data"
path: Array(5)
0: "paths"
1: "/x-unfetter-threat-boards"
2: "post"
3: "parameters"
4: "0"
length: 5
__proto__: Array(0)
results:
errors: Array(2)
0: {code: "INVALID_TYPE", message: "Expected type string but found type null", path: Array(3)}
1: {code: "INVALID_TYPE", message: "Expected type string but found type null", path: Array(3)}
length: 2
