### ISSUE TITLE
ff31 issues - Threat beta

### ISSUE THREAD

**Issue by j987987** [unfetter-discover/unfetter#1551]
In firefox 31, there are some visual bugs with threat beta

1. Reports carousel doesn't display properly

![image](https://user-images.githubusercontent.com/30236110/48086432-d64fd680-e1ca-11e8-9217-7c68f2154cfc.png)

2. Right sidebar doesn't have the polyfill CSS class so it overlaps content

![image](https://user-images.githubusercontent.com/30236110/48086478-faabb300-e1ca-11e8-8f54-af33c87ab1e3.png)

**Comment by j987987** [comment]
The issue with the transparent backgrounds is related to the fact that FF31 can't render linear-gradients as background images, so `[style.background-image]="getReportBackground(report)"` needs to be changed to `[style.background]="getReportBackground(report)"`

**Comment by webiator** [comment]
wrt the side panel, it appears FF31 is not recognizing the panel as consuming some of the available space in the content area. Not only are the sort buttons cut off, but the carousels are not displaying right arrows or pager buttons. FF31 does not know how wide the content should be.

**Comment by mpmmasterpeace** [comment]
I'm going to break this out since the global feed will require additional work. This way we can get the fixes in for the feed view now.

**Comment by mpmmasterpeace** [comment]
Follow on: #1560
