### ISSUE TITLE
Issue with adding a comment on demo board where user does not have an avatar

### ISSUE THREAD

**Issue by mpmmasterpeace** [unfetter-discover/unfetter#1566]
### Issue
Submitting a comment utilizes the user's avatar_url. This does not work on demo mode where the user does not have an avatar.

### Solution
Safely create an avatar url checking for existence. Use '' if it does not exist.
Also, for display, use an icon if user has no avatar.

**Comment by infosec-alchemist** [comment]
oh weird!
