### ISSUE TITLE
Viewing previous assessments gives 404

### ISSUE THREAD

**Issue by carnal0wnage** [unfetter-discover/unfetter#170]
attempting to view the previous acme assessments yields a 404

reproduction steps:
assessments tab --> clicking on a saved assessment

Error: Ember Data Request GET /cti-stix-store-api/x-unfetter-control-assessments/course-of-action--f342e7b3-30c7-4f01-830c-6c6ec4a7839e returned a 404 Payload (application/vnd.api+json; charset=utf-8) [object Object]

**Comment by infosec-alchemist** [comment]
Problem fixed and will be released in the next release
