### ISSUE TITLE
stix-ui relationship shows guid instead of name

### ISSUE THREAD

**Issue by carnal0wnage** [unfetter-discover/unfetter#171]
https://localhost/cti-stix-ui/relationships

shows a guid instead of the human readable name

<img width="1121" alt="screen shot 2017-04-28 at 2 33 05 pm" src="https://cloud.githubusercontent.com/assets/735360/25542260/c759b5ea-2c1f-11e7-938c-37725a6ca11f.png">

**Comment by infosec-alchemist** [comment]
Thanks for the suggestion.  We can try showing the page, with the relationship names, for each relationship type

**Comment by dev-jitsu** [comment]
The elements of the relationships page have been moved to other pages where it's easier to follow how stix objects are related.  The update will be available in the coming weeks.
