### ISSUE TITLE
Develop Mockups for Network Assessment Summary

### ISSUE THREAD

**Issue by infosec-alchemist** [unfetter-discover/unfetter#173]
Create sketch file dashboards for the Network Assessment Summary

**Comment by ADGCreative** [comment]
Hello. Attached is a zipped file containing a marked up PDF that annotates the choice of chart styles and the other is the sketch file. I tried to stick to font styles to be more consistent. please let me know if you have any questions, comments, or concerns. Thanks so much! (side note about the sketch file, many items are grouped. Is there is an asset you'd like to select, double click on that item until you final select the item. It may take 4-6 clicks.)

[unfetter_network_assessment_summary_wireframe_v1.zip](https://github.com/unfetter-discover/unfetter/files/990010/unfetter_network_assessment_summary_wireframe_v1.zip)

**Comment by infosec-alchemist** [comment]
When I open it, I get a message that some fonts are used but not found on my system:
Roboto-Regular
Centuma-Bold
Roboto-Black
Centuma-Light
Centuma

Are these fonts that were actually used?  Not sure how it will effect rendering.

**Comment by ADGCreative** [comment]
[NEW FILE — fonts are all Centuma]
Hello. Attached is a zipped file containing a marked up PDF that annotates the choice of chart styles and the other is the sketch file. I tried to stick to font styles to be more consistent. please let me know if you have any questions, comments, or concerns. Thanks so much! (side note about the sketch file, many items are grouped. Is there is an asset you'd like to select, double click on that item until you final select the item. It may take 4-6 clicks.)

[unfetter_network_assessment_summary_wireframe_v1.zip](https://github.com/unfetter-discover/unfetter/files/990095/unfetter_network_assessment_summary_wireframe_v1.zip)

**Comment by ADGCreative** [comment]
Font attached.

Let me know if you'd prefer we change over to a google font.

[Centuma.zip](https://github.com/unfetter-discover/unfetter/files/990098/Centuma.zip)

**Comment by infosec-alchemist** [comment]
We want to stick with a font that most users will have installed on their system and render in their browser.  Is that Centuma?

**Comment by ADGCreative** [comment]
Team,

We used Centuma for the wireframes, which is not a system font nor will most users have it installed on their machines. We could move over to the google font Roboto which browsers will support but most users will not have installed on their machines. Our next option would be to use one of the 11 system fonts though we tend to stick to Arial. Our recommendation would be to use the google font Roboto<https://fonts.google.com/specimen/Roboto>, something fresh with several varying font weights (light, regular, medium, bold, etc). Seeing as this application is text heavy, versus image heavy, we will want a font that is much more robust and adds personality or brand to the application. Arial is limiting in that is only have a few weights (regular, italic, bold, bold italic). Let me know if you’d like me to update the wireframe document with the Roboto font.

The fonts that are most safe to use are:
·         Arial / Helvetica<http://web.mit.edu/jmorzins/www/fonts.html#sans-serif>
·         Times New Roman / Times<http://web.mit.edu/jmorzins/www/fonts.html#serif>
·         Courier New / Courier<http://web.mit.edu/jmorzins/www/fonts.html#monospace>

Other options that usually work cross-platform are:
·         Palatino
·         Garamond

Fonts that work on Windows and MacOS but not Unix+X are:
·         Verdana
·         Georgia
·         Comic Sans MS
·         Trebuchet MS
·         Arial Black
·         Impact
http://web.mit.edu/jmorzins/www/fonts.html



—
Thanks,
Christina
