### ISSUE TITLE
Clicking on the campaign dashboard button doesn't show me how to create one

### ISSUE THREAD

**Issue by carnal0wnage** [unfetter-discover/unfetter#189]
The leftmost button is the campaigns button that takes me to https://localhost/unfetter-discover-ui/campaigns/dashboard aka "most recent campaigns" but i have no indication where to make one from this page

<img width="1304" alt="screen shot 2017-05-10 at 6 02 23 pm" src="https://cloud.githubusercontent.com/assets/735360/25923347/07ebcbfe-35ab-11e7-952f-0db91eb22625.png">

**Comment by threatinteltest** [comment]
Hi CarnalOwnage.  It is under the Settings/Stix Objects link.  When it takes you to the CTI-STIC-UI page it us under Campaigns.

**Comment by infosec-alchemist** [comment]
Thanks @carnal0wnage, we should put up an error message saying that there is no Campaigns listed.  We started making a campaign page, but we never gave it the bells and whistles.  Maybe we can also put up our mockup to show what we want it to look like.

**Comment by infosec-alchemist** [comment]
Like with Assessments, the dashboard pages should allow the creation of elements.  This should be implemented in the angular version
