### ISSUE TITLE
new indicator  should probably be new assessment

### ISSUE THREAD

**Issue by carnal0wnage** [unfetter-discover/unfetter#190]
https://localhost/unfetter-discover-ui/assessments

to start a new assessment someone has to click new indicator. It should probably want that to say new assessment?

<img width="1115" alt="screen shot 2017-05-10 at 6 07 46 pm" src="https://cloud.githubusercontent.com/assets/735360/25924529/2c2c5974-35b1-11e7-8d71-b29a5efabc00.png">

**Comment by infosec-alchemist** [comment]
- Task - Create a new first page of "new assessment" that lets you choice what you are assessing, so that the buttons aren't as confusing.
