### ISSUE TITLE
Assessments should be the leftmost option

### ISSUE THREAD

**Issue by carnal0wnage** [unfetter-discover/unfetter#192]
I believe the point of unfetter will be to map how my company fares against the ATT&CK phases and techniques, then Assessments should be the leftmost / important thing in the UI so we start with it.   It's currently to the right of campaigns.

<img width="1066" alt="screen shot 2017-05-10 at 6 54 06 pm" src="https://cloud.githubusercontent.com/assets/735360/25924684/14174686-35b2-11e7-944a-f82c7b5f1219.png">

**Comment by infosec-alchemist** [comment]
@ADGCreative , can you mockup an improved first page?
