### ISSUE TITLE
Assessments workflow issues (multiple)

### ISSUE THREAD

**Issue by carnal0wnage** [unfetter-discover/unfetter#193]
The assessment questions appear to ask questions from the CAR framework (https://car.mitre.org/wiki/Full_Analytic_List).  Unfortunately these questions are not a 1-1 mapping of the MITRE ATT&CK framework thus when you complete the assessment question flow i have blank sections.

Few comments (let me know if these need to be separate issues)

1. the questions should map to the MITRE techniques with questions to be able to guage my ability to alert to each technique.

2. The questions arent questions, they are statements. Most given no information on how i would ascertain my alerting capability to the analytic.

3. Unfetter needs to define what the options in the dropdown mean somewhere

4. Suggestion: each question could say something like "rate your ability to detect this:" about the pulldown of options

5. As described in CAR-2013-01-003 or whichever analytic  should be a hyperlink to that analytic. either on the internet or inside unfetter

6. The same question is coming up multiple times, this should be saved once and the same answer used for each ATT&CK phase. I shouldn't need to answer it multiple times.

**Comment by infosec-alchemist** [comment]
Item number 6 is coming out in the next release.  We will investigate 1-5.

**Comment by infosec-alchemist** [comment]
2. This is a good observation.  One problem with the way we separate the data from the display, is that whatever is used as the "name" of an analytic is what is posted on the screen.   We will have to evaluate that at a later time
3.  I will add this in another section
4.  I'll add this to the intro section
