### ISSUE TITLE
I dont see where to edit the answers to an assessment

### ISSUE THREAD

**Issue by carnal0wnage** [unfetter-discover/unfetter#194]
Once i have completed the initial assessment i dont seem to be able to edit it.

As mentioned in a previous issue, users arent being asked questions to map to all the techniques. This leaves me with unanswered/unrated ATT&CK techniques with no ability to update them.

<img width="1297" alt="screen shot 2017-05-10 at 6 32 26 pm" src="https://cloud.githubusercontent.com/assets/735360/25924947/9beb7f54-35b3-11e7-95f3-f2700127454d.png">

<img width="1251" alt="screen shot 2017-05-10 at 6 30 56 pm" src="https://cloud.githubusercontent.com/assets/735360/25924955/a4054058-35b3-11e7-8a15-fbee5420c1a0.png">

**Comment by infosec-alchemist** [comment]
Editing is in development right now. We expect to have it complete by our next delivery in 2 weeks.
