### ISSUE TITLE
attack patterns-->collection is missing items from ATT&CK

### ISSUE THREAD

**Issue by carnal0wnage** [unfetter-discover/unfetter#195]
https://localhost/cti-stix-ui/attack-patterns

the collection table is missing some items in the corresponding ATT&CK phase.  Unfetter should ship with all the techniques from ATT&CK as attack-patterns.

<img width="1111" alt="screen shot 2017-05-10 at 7 11 41 pm" src="https://cloud.githubusercontent.com/assets/735360/25925132/c3054a56-35b4-11e7-9f39-377c1391d4ac.png">

**Comment by infosec-alchemist** [comment]
We can add the attack patterns from the latest release of ATT&CK.

**Comment by carnal0wnage** [comment]
"Authentication Package" is missing from the Persistence Technique.  I assume it would be fixed once the new version is imported

**Comment by carnal0wnage** [comment]
'File System Permissions Weakness" I believe is currently named Service File Permissions Weakness which doesn't map to the current ATT&CK framework

**Comment by dev-jitsu** [comment]
The code to pull the MITRE data from github will be included in the next release.  It grabs the data on system startup so we shouldn't be missing any data when the site loads.

**Comment by infosec-alchemist** [comment]
I'm closing this ticket since the design is better articulated in #406
