### ISSUE TITLE
need a killchain description in the database

### ISSUE THREAD

**Issue by infosec-alchemist** [unfetter-discover/unfetter#206]
We need a consistent way to have a detailed description of a kill chain.  Right now, there are descriptions in the indicators and course of actions, but since this data can be changed/added, it isn't consistent.

In the Assessment Summary, the "weakness" area needs to have something specific.

**Comment by infosec-alchemist** [comment]
Add API's to pull kill_chain_phases from all objects, from object type, or from particular object ID's.

**Comment by infosec-alchemist** [comment]
Related to #352

**Comment by j987987** [comment]
Blocked on #411
