### ISSUE TITLE
Assessment questions default answer is nothing instead of unanswered 

### ISSUE THREAD

**Issue by carnal0wnage** [unfetter-discover/unfetter#256]
Hey!

While filling out a sample assessment i noticed the default is "Nothing" which is a valid answer but it should perhaps be some form of "unanswered" (But also with the 0 score)  that way as i fill this out i can tell more quickly if the answer is actually nothing/no coverage and its been filled in for me from a previous question or I just havent answered the question yet.

**Comment by infosec-alchemist** [comment]
We can differentiate 'unselected' from 'selected'.  An unselected should not actually be part of the Risk calculation, but the fact of "uncalculated" should be highlighted on the pages.

**Comment by infosec-alchemist** [comment]
Moving to later milestone in the interest of time.
