### ISSUE TITLE
Attack Pattern Formatting inside assessments

### ISSUE THREAD

**Issue by carnal0wnage** [unfetter-discover/unfetter#260]
Hi,

I updated an attack pattern to make it more readable by adding line breaks in the attack patterns STIX section. example: https://localhost/cti-stix-ui/attack-pattern/edit/attack-pattern--8024f8f7-39bb-4745-845b-71aa7a1ef940
<img width="1063" alt="attack-pattern-edited" src="https://user-images.githubusercontent.com/735360/27701166-0cde36d4-5cce-11e7-9d42-b7463c38d467.png">

After refreshing and going back to the page it looks like the update took.

Going onto a sample assessment the line breaks do not show up.  If i make other updates they show up on a refresh.

<img width="637" alt="attack-pattern-inside-assessment" src="https://user-images.githubusercontent.com/735360/27701226-33ba39f6-5cce-11e7-91da-60980c24e174.png">

**Comment by infosec-alchemist** [comment]
We will look at implementing readability in the ATTACK pattern descriptions.  Maybe use a simple markup language possibly?

**Comment by carnal0wnage** [comment]
i think a rudimentary markdown would be more than sufficient

**Comment by infosec-alchemist** [comment]
Markup is a longer discussion.  Moving to a later milestone to get it correct.
