### ISSUE TITLE
STIX objects should be in github so the community can add to them

### ISSUE THREAD

**Issue by carnal0wnage** [unfetter-discover/unfetter#261]
possibly related to https://github.com/unfetter-discover/unfetter/issues/253

But currently you cant download the various STIX json files from this GitHub repo and thus cant contribute updates for missing attack patterns or indicators or any of the other STIX objects.

Related to the above, is that a decision should be made on if the stix categories will be individual json files that get loaded into 1 or you'd want contributors to post their entire json file for any particular  category.

<img width="179" alt="stix objects" src="https://user-images.githubusercontent.com/735360/27702584-8b9c0e70-5cd2-11e7-983c-172d7b4fbb73.png">

**Comment by infosec-alchemist** [comment]
Thanks.  We are going to rethink how we break up the json files so that it supports contribution.

**Comment by infosec-alchemist** [comment]
We will support github URL's to be used as a location to load STIX data.  Unfetter will create its own STIX repository so that people can contribute there.
