### ISSUE TITLE
attack pattern rating inside assessment is not honoring STIX value

### ISSUE THREAD

**Issue by carnal0wnage** [unfetter-discover/unfetter#293]
I've created a new attack pattern in the STIX section, when i view it inside the assessment its not honoring the attacker sophistication value for some reason. I've set it as a 1 (novice) but it is showing as 3 (expert)

![screen shot 2017-07-20 at 12 31 37 pm](https://user-images.githubusercontent.com/735360/28428606-e8e62d7e-6d47-11e7-9ccf-aa15aad3c12f.png)

![screen shot 2017-07-20 at 12 31 27 pm](https://user-images.githubusercontent.com/735360/28428631-f6cb8a7e-6d47-11e7-851c-02e5a88466bd.png)

**Comment by infosec-alchemist** [comment]
Fixed
