### ISSUE TITLE
Handle duplicate STIX data objects in the processor import

### ISSUE THREAD

**Issue by dev-jitsu** [unfetter-discover/unfetter#302]
When MITRE data is imported from Github there are often duplicate entries.  The default stix.json bundle that ships with Unfetter often has the same data, but with different ids.  Take the MITRE data and ignore the data in stix.json in these cases.

**Comment by dev-jitsu** [comment]
Recommend waiting until the data structure is redisigned by @j987987.

**Comment by infosec-alchemist** [comment]
Unfetter should not "handle" duplicate data if the stix ID's are different.  This is a remnant of having duplicate data generated by the Unfetter team based on Mitre's attack data.  However, Mitre should be hosting their data, and Unfetter only host its own created data.

Therefore, we will remove the Mitre data from our GitHub repo and only use what comes from Mitre.
