### ISSUE TITLE
API error on app startup

### ISSUE THREAD

**Issue by dev-jitsu** [unfetter-discover/unfetter#309]
Occasionally there is the dreaded 'rlOrSO is required' error and the api shuts down.

The error from unfetter-ui is attached here (error message at the bottom is 'Unexpected token...') 

Most times all you need to do is stop the containers and re-run docker-compose.  It seems like a race condition getting the yaml file built.

![api-error](https://user-images.githubusercontent.com/24814771/29085810-6d4f421c-7c3e-11e7-9844-8472d4c48114.png)

**Comment by dev-jitsu** [comment]
I recommend using this in the docker-compose yml file.  I believe there is a race condition where the swagger.yaml file is needed but hasn't been fully assembled by 'multi-file-swagger and json2yaml'

entrypoint:
    - npm
    - start

instead of 

entrypoint:
    - npm
    - run
    - debugdev

**Comment by j987987** [comment]
nodemon.json has an event listener that recompiles the swagger file -after- nodemon relaunches the app.  It appears that nodemon will restart the app on save, the event will be trigger, and sometimes the new swagger file will be mid-compile when swagger express reads it.  Removing nodemon.json seems to fix it.
