### ISSUE TITLE
Allow Unfetter to update from a private git repo

### ISSUE THREAD

**Issue by underneith** [unfetter-discover/unfetter#315]
For organizations who may have proprietary data to use with Unfetter, would it be possible to have an option to also pull from a private git repo? Note: not in place of the public git repo, but in addition.

**Comment by infosec-alchemist** [comment]
Are you talking about a private github repo where you need credentials to access?  Or, are you requesting that it pulls from a git repo that is accessible from inside a local network, which would be the network that Unfetter is deployed?

**Comment by underneith** [comment]
Assume case where both credentials and git repo location would need to be specified to the application for connection.
