### ISSUE TITLE
Backend to support Threat Reports of other reports

### ISSUE THREAD

**Issue by infosec-alchemist** [unfetter-discover/unfetter#337]
For the Threat Report Dashboard, need the backend database to support a concept of creating a threat report based on other reports.  The threat report can be built off a STIX Report object, but needs to include the ability to track the boundaries that a Threat Report is created.

The Threat Report boundaries could be time frames, intrusion set(s), target identity(ies), attack pattern(s), object markings, malware, observable objects (ip, domain, etc).

There are relationship objects that support 'campaign attributed-to intrusion-set', 'campaign targets identity', and 'campaign uses attack-pattern,malware,tool'

This Threat Report might be more valid to be a Campaign object, which seems to support most of the valid values.  However, campaigns are supposed to focus only on a single intrusion set with a single mission.  A Threat Report might cross multiple intrusion sets or multiple objectives.

**Comment by mushinlogit** [comment]
To date, we are saving a Threat Report or Work Product as a metaProperties entry in a single STIX report object.  Where by many STIX report objects share a single Work Product.
