### ISSUE TITLE
Support concept of ownership, access roles inside of Unfetter

### ISSUE THREAD

**Issue by infosec-alchemist** [unfetter-discover/unfetter#344]
Using an access management system (oauth), support creating "groups" of users who have access to edit each other's work products as a team.  

Borrow the github "organization" and "team" models to start.  

- [ ] Allow Unfetter to be configured to support everyone has read/write, read, or no access.
- [x] Associate a user with a STIX ID
- [x] Allow self registration to Unfetter and into a basic group with read or read/write access
- [x] Allow movement of users from one group to another.
- [x] All new STIX items will store the user that created it via their STIX ID

**Comment by j987987** [comment]
separated the remaining concern of this issue into #654
