### ISSUE TITLE
Update the current "intrusion set dashboard"

### ISSUE THREAD

**Issue by infosec-alchemist** [unfetter-discover/unfetter#346]
Update the current "intrusion set dashboard" to become the "Threat Report dashboard".

The Threat report dashboard will show the results of all the individual stix reports that are put together for a Threat Report.

It will provide the Matrix similar to the current view.  It will list the boundaries identified down the left-hand side, with the ability to edit them.

If a particular matrix box/attack pattern is selected, the source report information will be displayed in a pane on the window.

Additional D3 graphs will provide other information including radar charts of attack pattern overlays, a tree graph showing related STIX data through discovery.  

It will also allow movement to other screens for the creation of new threat reports and editing the current one,

**Comment by mushinlogit** [comment]
pushed some of the minor features to sprint 1.2 issues
