### ISSUE TITLE
Attack Patterns no longer in downloadbundle

### ISSUE THREAD

**Issue by infosec-alchemist** [unfetter-discover/unfetter#351]
I can't seem to get attack-patterns to show up in the download bundle.  this is happening while I'm trying to rework the data loaded.  It might be something I am doing.

**Comment by j987987** [comment]
This problem was fixed by a commit for a different issue.

https://github.com/unfetter-discover/unfetter-discover-api/commit/851074f9da53379681e660287dd9d127bc7233d3
