### ISSUE TITLE
Allow Unfetter to import custom data from non stix datasource

### ISSUE THREAD

**Issue by infosec-alchemist** [unfetter-discover/unfetter#352]
The Mitre data, or data from other sources, will need enrichment data to support Unfetter.  This includes parameters like "sophistication level", or a way to group them.

Need to develop a backen schema approach to ingest, through unfetter-discover-processor, the encriched data separately from the core stix data. 

Need to develop screens in the UI to allow that enriched data to be created.  If at all possible, attempt to auto populate.  For instance, the indicators should be grouped by the kill chain that they fall under for the related attack pattern.

Support the decision to download the added properties separately, and together, in the data download.

**Comment by j987987** [comment]
Blocked on #411
