### ISSUE TITLE
Grouping Assessments

### ISSUE THREAD

**Issue by infosec-alchemist** [unfetter-discover/unfetter#353]
The use of kill-chain.phase-name for grouping indicators, sensors and coa's in assessments is not an appropriate use of "kill-chain".  COA's don't have kill chains.

However, it's necessary to group those objects so that the survey pages are not super long.

EITHER, create a group by an extended field that is ingested as a STIX extended field for Unfetter, and support the UX CRUD to change that field, or:

Group the assessed objects in the assessment create/edit screens by the kill-chain phase of the related attack-patterns.  In other words, get the related attack-patterns for each assessed object (indicator, sensor, coa) and group those by the related kill chain.

Likely, we might want the groups to be the same as the Kill Chains.  Consider making kill chain a default, or using a group object if that group object exists.

**Comment by infosec-alchemist** [comment]
Dependant on #352

**Comment by j987987** [comment]
Blocked on #411
