### ISSUE TITLE
Sightings create page doesn't work

### ISSUE THREAD

**Issue by infosec-alchemist** [unfetter-discover/unfetter#365]
The sightings create page doesn't appear to work.  After entering the information and clicking "save and close", the page shows both the list page and the add form on the same page.  however, the list doesn't show the created sighting

**Comment by infosec-alchemist** [comment]
When I delete a sighting, nothing happens.

When I create a sighting, save it, then go back to the edit sighting, the summary is blank.

When I try and save an edit summary, I get a 400 error.  looking at the request, it doesn't appear to support the json-api model.  all the data is at the top level of the object.

**Comment by j987987** [comment]
This appears to be fixed.

**Comment by infosec-alchemist** [comment]
Agreed.  It has been fixed.
