### ISSUE TITLE
Intrusion Set create form error

### ISSUE THREAD

**Issue by infosec-alchemist** [unfetter-discover/unfetter#367]
A 400 error occurs when creating an Intrusion Set

Error 400 - Bad Request {"errors":[{"status":400,"source":"","title":"Error","code":"","detail":["`aa` is not a valid enum value for path `stix.primary_motivation`.","`aaa` is not a valid enum value for path `stix.resource_level`."]}]}

**Comment by j987987** [comment]
Was fixed with another issue.
