### ISSUE TITLE
some open-vocab values are treated as closed-vocab

### ISSUE THREAD

**Issue by infosec-alchemist** [unfetter-discover/unfetter#369]
In the API, the open-vocab properties, like motiviations and resource level in Intrusion Sets are being forced to be from the identified vocab.  however, those are suggestions and we should allow the option to write their own. 

The API needs to remove the requirement for forcing the open vocab.

The CRUD UI should provide a drop down list or other mechanism to let users select the value they want.  However, they should also have the option of writing their own.

Some open-vocabs are a list of vocabs (strings).  For those, the UI should provide a list of what is selected.

**Comment by j987987** [comment]
This issue is most likely fixed.  Added review status.
