### ISSUE TITLE
Creating a sensor and a mitigations assessment makes two sensors

### ISSUE THREAD

**Issue by infosec-alchemist** [unfetter-discover/unfetter#375]
I created an indicator, then mitigation, then sensor assessment.

when I got to edit each of them, the sensor and the mitigations edit appears to be the same assessed values.

However, the Mitigations Assessment Dashboard appears to be correct.  This is only happening in Edit.

**Comment by mushinlogit** [comment]
this was probably fixed in issue #389

**Comment by infosec-alchemist** [comment]
Verified it was fixed.
