### ISSUE TITLE
Dashboard breaks when editing values

### ISSUE THREAD

**Issue by infosec-alchemist** [unfetter-discover/unfetter#377]
When I go back to editing indicators, set all values to 0% risk (all green), the dashboard breaks.  All risks are N/A

**Comment by j987987** [comment]
I did see this occur once but I'm having a hard time reproducing it.

**Comment by infosec-alchemist** [comment]
I will try and recreate again

**Comment by infosec-alchemist** [comment]
Okay, this doesn't "Break" with N/A.
