### ISSUE TITLE
Assessment Dashboard missing risk level per attack pattern

### ISSUE THREAD

**Issue by infosec-alchemist** [unfetter-discover/unfetter#382]
The numeric representation of the risk value of an attack pattern, when a specific attack pattern is clicked, is missing.  Add in the Attack Pattern details, the risk value.  That value should change as assessed objects are changed

**Comment by j987987** [comment]
Fixed with 384

**Comment by infosec-alchemist** [comment]
I dont' see this risk level.

On the assessment detailes page, in the third column, it should be written right under "Sophistication Level"

**Comment by j987987** [comment]
https://github.com/unfetter-discover/unfetter-ui/pull/44
