### ISSUE TITLE
Editing assessed values in Assessment Dashboard doesn't correctly update risk level icon

### ISSUE THREAD

**Issue by infosec-alchemist** [unfetter-discover/unfetter#384]
When editing an assessed object in the assessment dashboard (third column), changing the values will change the risk value of the assessed object, but it does not change the red to green dot for the specific attack pattern.

Also, the risk value for the entire kill chain does not recalculate either.

**Comment by infosec-alchemist** [comment]
This is still not working.

I created an assessment.  I clicked on an attack pattern.  There were three indicators associated.  I changed every one of those risk levels to be 100%.  The resulting risk, which did change, is at 42%.  Also, the color is green and never changed.

**Comment by j987987** [comment]
The risk icon appears to updating, but the calculations are incorrect for some assessments.  I changed that to be the focus of the issue.

**Comment by j987987** [comment]
Mongo query to validate assessments being constructed correctly.  No assessment object should appear more than once.

```db.getCollection('stix').aggregate([
{
    $match: {'stix.id': // stix id here }
},
{       
    $unwind: '$stix.assessment_objects'
},
{
    $group: {
        _id: '$stix.assessment_objects.stix.id',
        count: {
            $sum: 1
        }
    }
},
{
        $sort: {count: -1}
},
])```

**Comment by mushinlogit** [comment]
Used query,
``` db.getCollection('stix').aggregate([
{
    $match: {'stix.id': /* assessment id */ }
}
])
```
