### ISSUE TITLE
Editing mitigations assessments displays sensor assessment information

### ISSUE THREAD

**Issue by j987987** [unfetter-discover/unfetter#389]
To recreate:
1) Create a mitigations assessment
2) From the assessments list, select edit on that assessment

You will see the sensor assessment data.

When save is selected, the PATCH request will have the original "assessment_objects", however the saving of edited name and description seems to work.

**Comment by infosec-alchemist** [comment]
may be related to #issue-375

**Comment by mushinlogit** [comment]
unfetter-discover/unfetter-ui#46

**Comment by mushinlogit** [comment]
editing mitigations will now correctly render the mitigation assessment and not a sensor assessment.  There is still a problem with blank values on edit and next/prev clicking, capture in #376.  Closing this issue.
