### ISSUE TITLE
Intrusion Set Dashboard - No intrusion sets selected errors

### ISSUE THREAD

**Issue by j987987** [unfetter-discover/unfetter#390]
If the user clicks "search" with no intrusion sets checked, it will hit the api with `https://localhost:9443/api/dashboards/intrusionSetView?intrusionSetIds=`, and more importantly, it causes a javascript error with an attempt to loop over an undefined collapsible tree and it will created duplicate "Kill Chain Phases Used" sliders.

**Comment by mushinlogit** [comment]
fixed by unfetter-discover/unfetter-ui#41
