### ISSUE TITLE
Minimize use of default values in the UI STIX model classes

### ISSUE THREAD

**Issue by j987987** [unfetter-discover/unfetter#391]
The STIX model classes have a `createAttributes()` method that sets the default values of its attributes.

This practice is problematic in some cases, such as `x_unfetter_sophistication_level` where `0` is a valid value.  The default value of `-1` was cause bugs elsewhere in the program.

For some other problems, like `kill_chain_phases`, a default value of an empty array is needed since the forms assume it has a array methods.

Removing default values will mean that on a POST request that the property will only be there is a value was assigned in the form.

**Comment by infosec-alchemist** [comment]
Evaluate to make sure that the UI is filling in those default values on default (like dates) rather than relying on the API to support it.
