### ISSUE TITLE
There are too many warnings in the Unfetter-Ui build

### ISSUE THREAD

**Issue by infosec-alchemist** [unfetter-discover/unfetter#394]
When Unfetter-Ui builds, there are too many warnings.  We want to have a clean build, so these warnings need to be evaluated and handled.  More issues can be created if the changes are significant.

**Comment by mushinlogit** [comment]
These npm scripts now run with out major warnings;
npm run server:dev:alt
npm run server:local:dev
npm run clean
npm run build

These npm scripts almost run without warnings.  I am closing this issue and capturing in another issue;
npm run build:aot
npm run typedoc
