### ISSUE TITLE
Implement and Enforce Object Markings

### ISSUE THREAD

**Issue by infosec-alchemist** [unfetter-discover/unfetter#40]
<a href="https://github.com/infosec-alchemist"><img src="https://avatars.githubusercontent.com/u/19472140?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [infosec-alchemist](https://github.com/infosec-alchemist)**
_Wednesday Sep 28, 2016 at 18:24 GMT_
_Originally opened as https://github.com/iadgov/unfetter-discover/issues/108_

----

Implement and enforce object markings per user access.

**Comment by webiator** [comment]
STIX marking definitions are:
- A simple TLP (traffic light protocol) or free-flow text (called a statement) value. Nothing more complex.
- Can be applied to entire STIX objects, or to properties of those objects.
- Multiple marking definitions can be applied. No restrictions on any of them.
 
- [x] Need a page for displaying marking references
- [x] Need a page for entering marking references
- [ ] Need a component to add multiple marking references to a ... thing. Such as other STIX objects, assessments, threat reports, etc.
- [ ] Need to allow site customization, such as allowing CAPCO.
-- CAPCO values would involve a category, the text, and portion marking. Categories would include classification, compartments, accesses and disseminations (and others for foreign markings).
-- could require one, and restrict multiple, CAPCO classification markings, and permit 0 or more of the other categories
-- display of an object would need a custom renderer for something like CAPCO
-- customer site may require only one marking reference type or another (such as only TLP or CAPCO)
-- Creating marking refs with such customization means we need some way to inject code for the "new" page (html, css and js)

**Comment by webiator** [comment]
- [x] Filter is written (needs merging)

Proposal for assigning marking_refs to users:
- [ ] Org Leaders should have permission to add marking definitions pertinent to their org. Every user in the org should receive these markings.
  - [ ] But only admins can go to the STIX pages. Well, maybe org leaders should, too. After all, an "admin" role should be there to manage Unfetter, not its data (separation of roles). Orgs would have data pertinent to them that no admin would even know about (such as new threat actors or campaigns). Maybe keep some data protected (like, why would anyone be modifying attack patterns??).
  - [ ] Any marking added by an admin would be automatically "public," meaning an org leader can add it to their org without restriction.
  - [ ] Any marking created by an org leader would be automatically added to their org.
  - [ ] Default authentication behavior would be to grab all the markings in the orgs the user is a member of, and apply them to the user, at login time.
  - [ ] Custom implementations would take markings returned from the authentication service and apply them to the user at login. Any belonging to the orgs they are members have can optionally be merged in (for instance, on high side, we would likely throw out all the CAPCO markings applied to the org and go solely with that provided by the service; non-CAPCO could still be used).
  - [ ] The user document marking_refs array in both cases could be used to apply user-specific markings in some future version.

**Comment by webiator** [comment]
Other thought, about the CAPCO code (but no actual markings) existing in the base code:
- [ ] Could add a configuration flag that turns the feature off (off by default).

**Comment by webiator** [comment]
unfetter-discover/unfetter#1324 takes over from here.
