### ISSUE TITLE
Rewrite unfetter-discover-processor

### ISSUE THREAD

**Issue by j987987** [unfetter-discover/unfetter#411]
Currently the processor has a large amount of code that is no longer used / relevant, and the arg parsing is buggy.

The processor should be rewritten in a more efficient, with a stronger arg parsing library like [yargs](https://github.com/yargs/yargs).  The new processor should also handle connecting and disconnecting to MongoDB more gracefully.

Full docker integration is possibly blocked on #253, due to the processor project going away.

**Comment by mushinlogit** [comment]
Make sure to delete the mongo db folder and rebuild the processor docker images.  Looks good and is merged
