### ISSUE TITLE
Evaluate Git Flow

### ISSUE THREAD

**Issue by infosec-alchemist** [unfetter-discover/unfetter#435]
Evaluate implementing Git Flow for managing branches.

https://datasift.github.io/gitflow/IntroducingGitFlow.html

**Comment by mushinlogit** [comment]
To [install gitflow](https://github.com/nvie/gitflow/wiki/Mac-OS-X)
`cd gitproject`
`git flow init`
Set to master, default, and issue- for the prompts.  We could adopt the feature/, hotfix/, folder like naming convention, but our issue- works as well.

To work in gitflow
`git flow feature start <feature name>`
`git add <files>`
`git commit -m "issue number"`
`git flow feature publish <feature name>`
`git flow feature finish <feature name>`
