### ISSUE TITLE
Minor change to Assessment Dashboard Summary

### ISSUE THREAD

**Issue by infosec-alchemist** [unfetter-discover/unfetter#455]
Please add the color indicator next to the assessed ATTACK Patterns in the middle column of a selected Kill Chain in the Assesssments Dashboard

![screen shot 2017-09-21 at 10 57 03 am](https://user-images.githubusercontent.com/19472140/30702791-eacea90e-9ebb-11e7-85cb-52332c76ddc4.png)

**Comment by j987987** [comment]
This error was resolved in a PR for a different issue.
