### ISSUE TITLE
Adding relationships between new attack-patterns and course-of-actions

### ISSUE THREAD

**Issue by jburns12** [unfetter-discover/unfetter#476]
When creating a new attack pattern, the option of adding a mitigation to an attack pattern should generate a course of action and corresponding relationship between the two.

Cannot self assign, but will make a PR containing this capability to the develop branch of unfetter-ui once it is implemented.

**Comment by infosec-alchemist** [comment]
Being worked by @jburns12.

**Comment by jburns12** [comment]
Merged in commit 53a1919f5546a082f2bb8f43e6d5102211724411 of unfetter-ui.
