### ISSUE TITLE
latest build looks for a file in a folder that does not exist

### ISSUE THREAD

**Issue by carnal0wnage** [unfetter-discover/unfetter#494]
EDIT:

documentation needs to be updated

-----

docker-composer up looks for a file that is not present

unfetter-store/unfetter-ctf-ingest

cg@ovelr0rd ~/Documents/defense $ mkdir unfetter-discover
cg@ovelr0rd ~/Documents/defense $ cd unfetter-discover
cg@ovelr0rd ~/Documents/defense/unfetter-discover $ git clone https://github.com/unfetter-discover/unfetter.git
Cloning into 'unfetter'...
remote: Counting objects: 921, done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 921 (delta 3), reused 13 (delta 2), pack-reused 902
Receiving objects: 100% (921/921), 124.94 MiB | 11.47 MiB/s, done.
Resolving deltas: 100% (398/398), done.
cg@ovelr0rd ~/Documents/defense/unfetter-discover $ cd unfetter
cg@ovelr0rd ~/Documents/defense/unfetter-discover/unfetter (master) $ docker-compose up
ERROR: build path /Users/cg/Documents/defense/unfetter-discover/unfetter-store/unfetter-ctf-ingest either does not exist, is not accessible, or is not a valid URL.

**Comment by vac4n7** [comment]
hey @carnal0wnage, I ran into the same issue a few days ago and got it to compose by cloning these two repos into the same unfetter-discover directory you created:
`git clone https://github.com/unfetter-discover/unfetter-store.git`
`git clone https://github.com/unfetter-discover/unfetter-ui`

probably still an issue as the documentation doesn't mention you need to do this, but figured I'd chime in

**Comment by carnal0wnage** [comment]
ty i'll try that

**Comment by carnal0wnage** [comment]
ok that does work. gonna edit to say they need a documentation update. 

thanks tons for the comment @vac4n7

**Comment by carnal0wnage** [comment]
stuck at

unfetter-discover-processor       | Mongoose connection error: MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
unfetter-discover-processor       | Mongoose connection error: MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
unfetter-discover-processor       | Mongoose connection error: MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
unfetter-discover-processor       | Mongoose connection error: MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
unfetter-discover-processor       | Mongoose connection error: MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
unfetter-discover-processor       | Mongoose connection error: MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
unfetter-discover-processor       | Mongoose connection error: MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
unfetter-discover-processor       | Maximum number of connection attempts exceeded. Terminating program.

now

**Comment by j987987** [comment]
This should fix it.  Use this for your docker.compose.yml file.

https://gist.github.com/j987987/b000d51a557fb5f9bd53b5cbcc36a6bd

**Comment by infosec-alchemist** [comment]
In general, we have two installations.  The Master branch pulls docker images from DockerHub and builds the official release version.  For developers, you would need to clone the other repo's, move to the develop branches of those repo's, and run the docker-compose.development.yml file.

In this case, we accidentally added an upcoming capability to the master compose file.   We just patched the master repo so everything SHOULD work.  Let us know if it doesn't.
