### ISSUE TITLE
Unfetter Webpage Edits

### ISSUE THREAD

**Issue by KRobinson-ADG** [unfetter-discover/unfetter#507]
- [ ] The hyperlinks in the footer of the first page are showing in blue (as hyperlink format) but were designed grey to blend in more as buttons. (d5d5d5)

- [ ] Look at any policy, license, etc information that needs to be added

- [ ] The footer doesn’t always stick to the bottom of the page on some of the secondary pages (I’m looking at the STIX 2.0 Design page as an example). There is white space below the footer since the copy on the page itself is short 

- [ ] The footer on the “The Future of Unfetter” page does not link to Feedback or Terms

- [ ] The grey background can be removed from the “The Future of Unfetter” page to match other secondary pages

- [ ] Change to hamburger menu.  Have it close when anywhere on the screen is clicked, not just the X.

- [ ] On a full size computer, you have to move the mouse to the middle of the screen to select. A smaller drop down on the right hand side would be less jarring

- [ ] Content change: remove 'Unfetter Insight will' from the text above the items in the 'Future of Unfetter' section

**Comment by infosec-alchemist** [comment]
The footer sticking to the bottom still needs to be fixed

**Comment by infosec-alchemist** [comment]
Moving to the main unfetter webpage repo github project

www.github.com/iadgov/unfetter
