### ISSUE TITLE
Indicator Labels in the "indicator hub" should support indicator-label-ov

### ISSUE THREAD

**Issue by infosec-alchemist** [unfetter-discover/unfetter#533]
All stix objects have a "label" which is an array of strings.  Some STIX objects allow any strings.  Others, like indicators, have a set of labels that "SHOULD" be used.

We want to drive people to those labels in indicators so that we can group indicators.  But, there should be the option to create one of their own.

We should allow the label created to have a checkbox for the standard labels, and then a box for entering their own

anomalous-activity, anonymization, benign, compromised, malicious-activity, attribution

**Comment by j987987** [comment]
blocked on #535
