### ISSUE TITLE
Make links to external references clickable

### ISSUE THREAD

**Issue by dmoore44** [unfetter-discover/unfetter#547]
It would be helpful if links to external references (i.e. the little yellow and blue bubbles associated with objects) were clickable.  It appears that they're currently rendered as text on a page, rather than web link.

**Comment by infosec-alchemist** [comment]
For which page is this referring to?  Can you provide the URL?

**Comment by dmoore44** [comment]
All of them, but as a visual example, here's a screen shot taken from the Remote File Copy attack pattern illustrating what I'm referring to.

![attack-patterns](https://user-images.githubusercontent.com/3177656/32556414-f99158a0-c464-11e7-8474-0c4e9e0e801b.png)
