### ISSUE TITLE
Support multiple frameworks, such as the Mobile ATT&CK

### ISSUE THREAD

**Issue by infosec-alchemist** [unfetter-discover/unfetter#560]
Implement the ability to have multiple frameworks in the system for Attack Patterns.

[ ] - Multiple Kill Chains can be loaded,  by using the kill-chain-phase.kill_chain_name to distinguish the frameworks.
[ ] - The user will have to determine which framework they are using at a time.  Everything is Displayed based on that framework.  
[ ] - Show all other data (indicators, sensors, etc) if they have no relationship to an attack pattern
[ ] - If a STIX data (indicator) is related to an Attack pattern, but that attack pattern IS NOT part of the currently viewed framework, then it is treated as unrelated object.
[ ] - The currently working framework should be remembered for a particular user. 
[ ] - A configuration environment variable at startup will select the default framework.

**Comment by j987987** [comment]
A lot has been done in regards to this in recent months, the steps of the issue should be updated.
