### ISSUE TITLE
Typographic error in the description of "Intrustion Sets" under "STIX Objects"

### ISSUE THREAD

**Issue by 0xenigmark** [unfetter-discover/unfetter#564]
Original: 
 An Intrusion Set is a grouped set of adversarial behaviors and resources with common **propertiesthat** is believed to **believedorchestrated** by a single organization. An Intrusion Set may **caputre** multiple Campaigns **organizationother** activities that are all tied together by shared attributes indicating a **commont** known or unknown Threat Actor. Threat Actors could move from supporting one Intrusion Set to supporting another, or may support multiple at the same time.

Items which need review are in bold.

**Comment by infosec-alchemist** [comment]
Thanks for letting us know.
