### ISSUE TITLE
Link explorer graphing tool does not seem to be rendering properly on Chrome

### ISSUE THREAD

**Issue by 0xenigmark** [unfetter-discover/unfetter#567]
Link explorer visualization does not seem to be rendering properly.

Inability to click and and drag to explore the relationship between assets.

![unfetter-linkexplorer](https://user-images.githubusercontent.com/25191579/32826421-41eba66e-ca23-11e7-97ae-cb1077d3a628.PNG)

Platform: Chrome 56.0.2924.76  (x64)

**Comment by infosec-alchemist** [comment]
This functionality will likely not be updated.  We are pursuing better ways to display this data.
