### ISSUE TITLE
Environment proxy not honored by unfetter-discover-processor

### ISSUE THREAD

**Issue by johnwunder** [unfetter-discover/unfetter#579]
The "fetch" library used by unfetter-discover-processor does not respect the environment's proxy settings by default (see: https://github.com/bitinn/node-fetch/issues/195)

I was able to work around this by changing some code in `processor.js`, but it would be nice to just have it honor the environment's proxy (example of how to do that is in the URL I referenced).

**Comment by j987987** [comment]
https://github.com/unfetter-discover/unfetter-store/pull/72
