### ISSUE TITLE
Sign-in button sends a GET request to an invalid URI

### ISSUE THREAD

**Issue by 0xenigmark** [unfetter-discover/unfetter#580]
unfetter-discover-gateway         | 2017/11/20 14:56:32 [error] 5#5: *3 connect() failed (111: Connection refused) while connecting to upstream, client: /sanitized/, server: localhost, request: "GET /api/auth/github-login/ HTTP/2.0", upstream: "https:///172.18.0.2/:3000/auth/github-login/", host: "unfetter.sanitized.tld", referrer: "https://unfetter.sanitized.tld/"

Application is tested on a google cloud instance.

Service is started by the following command: docker-compose -f docker-compose.development.yml up

**Comment by infosec-alchemist** [comment]
For the development installation, it supports UAC now.  Were you able to follow the UAC setup at https://github.com/unfetter-discover/unfetter/wiki/GitHub-UAC-Configuration

**Comment by j987987** [comment]
Alternatively, you could set run mode to demo.

https://github.com/unfetter-discover/unfetter/wiki/Unfetter-Build-Types-&-Run-Modes

**Comment by 0xenigmark** [comment]
When following the UAC setup, the following error occurs when accessing the landing page of unfetter running in UAC mode using the docker-compose.deploy.yml file

unfetter-discover-gateway         | 2017/11/21 06:02:23 [error] 5#5: *4 directory index of "/etc/nginx/html/" is forbidden, client: /sanitized/, server: localhost, request: "GET / HTTP/2.0", host: "unfetter.tld"

unfetter-discover-gateway         | sanitized - - [21/Nov/2017:06:02:23 +0000] "GET / HTTP/2.0" 403 571 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.76 Safari/537.36" "-"

unfetter-discover-gateway         | 2017/11/21 06:02:24 [error] 5#5: *4 rewrite or internal redirection cycle while internally redirecting to "/index.html", client: sanitized, server: localhost, request: "GET /favicon.ico HTTP/2.0", host: "unfetter.tld", referrer: "https://unfetter.tld/"

unfetter-discover-gateway         | sanitized - - [21/Nov/2017:06:02:24 +0000] "GET /favicon.ico HTTP/2.0" 500 595 "https://unfetter.tld/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.76 Safari/537.36" "-"

Results in a 403.

Using the docker-compose.development.yml file in UAC mode works OK.

**Comment by infosec-alchemist** [comment]
This should be fixed in #release 0.3.3
