### ISSUE TITLE
Analytics should be able to have multiple patterns of different pattern types

### ISSUE THREAD

**Issue by johnwunder** [unfetter-discover/unfetter#591]
A user contributing an analytic should be able to add multiple patterns. Each pattern should probably also be tagged with a pattern type (pseudocode, STIX, Splunk, etc).

**Comment by infosec-alchemist** [comment]
Since this would deviate from STIX, should the taxii server exchange this information

**Comment by j987987** [comment]
This functionality was added through another issue.
