### ISSUE TITLE
Addition of MITRE's pre-attack matrix

### ISSUE THREAD

**Issue by 0xenigmark** [unfetter-discover/unfetter#592]
https://attack.mitre.org/pre-attack/index.php/Main_page

Any chance for this to be added? Might be a useful tool to help organisations understand and map their opsec exposure and the possible methods which might be used by a threat actor targeting them.

**Comment by infosec-alchemist** [comment]
We will add this when Mitre provides the STIX data. 

And, we have the ability to show multiple frameworks.  Thats on the list for January
