### ISSUE TITLE
Restrict assessments to creation organization

### ISSUE THREAD

**Issue by infosec-alchemist** [unfetter-discover/unfetter#612]
Make it so that assessments are only viewable/editable by the organization that created the assessment.

This should only happen when User Access is enabled.  

Allow for "global organizations" to support demo.  The global organization may just be the organization that everyone who signs up with that instance of Unfetter is apart of automatically.  

The global organization can act as a "view by all" grouping.

**Comment by mushinlogit** [comment]
@infosec-alchemist should this be considered done at this point?  We have a `unfetter-open` global org, and a security filter being applied to our rest calls.

**Comment by mushinlogit** [comment]
OBE, this was implemented under the security filter work
