### ISSUE TITLE
Unfetter-Ui Build error

### ISSUE THREAD

**Issue by infosec-alchemist** [unfetter-discover/unfetter#618]
For deploy mode, the following error occurs when running docker-compose.deploy.yml

Error: Metadata version mismatch for module /usr/share/unfetter-ui/node_modules/primeng/components/dom/domhandler.d.ts, found version 4, expected 3

**Comment by mushinlogit** [comment]
was able to duplicate by running `npm run build:aot:prod:noclean`

**Comment by mushinlogit** [comment]
was able to duplicate by running `npm run build:aot:prod:noclean`

primeng was expecting Angular 5.  Downgraded to primeng 4.3 and Angular 4.4.4 and seemed to fix the issue
