### ISSUE TITLE
Date Picker shows red

### ISSUE THREAD

**Issue by infosec-alchemist** [unfetter-discover/unfetter#64]
<a href="https://github.com/infosec-alchemist"><img src="https://avatars.githubusercontent.com/u/19472140?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [infosec-alchemist](https://github.com/infosec-alchemist)**
_Friday Jan 13, 2017 at 20:06 GMT_
_Originally opened as https://github.com/iadgov/cti-stix-services/issues/79_

----

For indicators and sightings, even when entering a date, the date picker is showing red, indicating that it is a required field.  This happens even if a valid date has been picked.

**Comment by dev-jitsu** [comment]
Fixed, PR merged
