### ISSUE TITLE
Implement empty assessments page (0 created)

### ISSUE THREAD

**Issue by mushinlogit** [unfetter-discover/unfetter#640]
Per mockup redesign

Implement the 0 assessments created page

supports parent, unfetter-discover/unfetter#636

**Comment by infosec-alchemist** [comment]
Kibana also does a good job.  When you start, and there are no dashboards, you get the message

"Looks like you don't have any dashboards.  Let's create some!"  and then a big button that says "create dashboard"

I like that conversational tone and there is no guesswork as to what the user needs to do next

**Comment by mushinlogit** [comment]
currently this was implemented as an intelligent route.  If the user has not assessments, a create page is shown, else the user has assessments and the last modified was shown.  Also for demo mode w/ no concept of user the query works across all assessments in the system
