### ISSUE TITLE
Read permissions based on organization

### ISSUE THREAD

**Issue by j987987** [unfetter-discover/unfetter#654]
The difficulty in creating organization-based read permissions is modifying the mongo queries without introducing bugs, while at the same time taking roles into consideration.  Middleware would have to be added to the API to edit the incoming queries to accomplish this.  Existing mongo aggregation pipelines would also have to be edited.

An organization may also want to allow another organization(s) to read its data, which would make this middleware even more complicated.  This should be controllable in the organization management dashboard.

**Comment by infosec-alchemist** [comment]
@j987987 , can this be closed?

**Comment by j987987** [comment]
It has not been completed, pushing it to next sprint.
