### ISSUE TITLE
Develop/Publish data model for Assessments 3.0

### ISSUE THREAD

**Issue by infosec-alchemist** [unfetter-discover/unfetter#661]
Please provide the following:

- [x] Document a proposed data model for Assessments 3.0 that fits the current data model schemas, but supports the Assessments 3.0 needs
- [X] Get reasonable consensus from @mushinlogit and team
- [x] Document any translations between STIX data and the data model
- [x] Build necessary schemas

**Comment by sbertrandmitre** [comment]
Data model is currently published on the Unfetter CoDev site hosted by Mitre: 
 https://wiki.codev.mitre.org/display/UNFETTER/Assessments+3.0+Data+Model

**Comment by joe-dam** [comment]
Schemas are in PR https://github.com/unfetter-discover/unfetter-store/pull/120
