### ISSUE TITLE
Add heatmap for techniques

### ISSUE THREAD

**Issue by dmoore44** [unfetter-discover/unfetter#666]
Using the Assessments functions in Unfetter is useful for risk scoring and providing a risk-based view of security posture, but I think that a heatmap view of techniques would make for a good way to visualize posture in a relative sense, and provide a convenient executive dashboard.

See Roberto Rodriguez's blog post (towards the bottom) for details: https://cyberwardog.blogspot.com/2017/12/ready-to-hunt-first-show-me-your-data.html

Or, direct download to the XLS file: https://github.com/Cyb3rWard0g/ThreatHunter-Playbook/blob/master/metrics/HuntTeam_HeatMap.xlsx

**Comment by sbertrandmitre** [comment]
This type of view will be required for Assessments 2.0, which features a coverage heatmap similar to that found at the links above.

**Comment by webiator** [comment]
Issue 666, oh my.

**Comment by infosec-alchemist** [comment]
closing, since we are tracking more details for this requirement in #753
