### ISSUE TITLE
Add Ability to Edit Analytics Directly From the Analytic Hub

### ISSUE THREAD

**Issue by ikiril01** [unfetter-discover/unfetter#673]
Currently, one has to go through the STIX Objects in order to edit any Analytics stored in the Analytic Hub - it would be great (and less confusing for users) if this could be done directly through the Analytic Hub itself.

**Comment by infosec-alchemist** [comment]
- [ ] Support edit directly from the Analytic Hub
- [ ] Edit only if you are part of the organization that created it
- [ ] The Edit modal should be of the same style as the add modal

**Comment by j987987** [comment]
Currently on develop, there is a menu on the upper right of each analytic card to edit / delete analytics.  The "edit" button is a link to an edit screen in the STIX Object pages, however the cancel and save buttons will take you back the analytic hub when that link is used.  (This is just a FYI, not feedback on the issue)

**Comment by j987987** [comment]
I'm adding edit functionality to the stepper, however for this issue I'm going to turn off the relationship tool during edit and do that in a separate issue, since there a lot of edge cases with that.
