### ISSUE TITLE
Need an Attack Pattern Chooser

### ISSUE THREAD

**Issue by infosec-alchemist** [unfetter-discover/unfetter#676]
We need a better way to let users, who are creating/editing objects, select the related "attack patterns"

Currently, we do it through a combination of search boxes or drop downs.  We need a better way to let people either search when they know what they want, or to be able to select via the categories.  A big tree view is possible but is hard to manage.  Need something better.

**Comment by j987987** [comment]
A tree view similar to the "Observable Data" tree with kill chain phases as the drop downs would be possible.  

A checklist with a search bar and a multi-select to select kill chain phases would be another idea.

**Comment by dmoore44** [comment]
Perhaps you could invert your use case.  Instead of creating objects and then associating them with attack patterns, allow users to create new objects when browsing through the attack patterns.

**Comment by webiator** [comment]
Perhaps the heatmap would work?

**Comment by infosec-alchemist** [comment]
A control for selecting based on the heatmap will be introduced into the assessment 3.0 efforts.  Closing this Issue since the design has been created
