### ISSUE TITLE
autoselect data objects from STIX Pattern

### ISSUE THREAD

**Issue by infosec-alchemist** [unfetter-discover/unfetter#680]
When a stix pattern is entered into the Analytic Hub, use the stix2pattern/get-objects API to get a list of data objects, and pre select the data objects section of the analytic.

Specifically, use it to show what data objects have been selected if a valid pattern was entered.  If a valid pattern was not entered, then allow the selection through the tree.

**Comment by j987987** [comment]
By accident, I wrote this same issue in #684.  It's completed.
