### ISSUE TITLE
Add travis.yml for all projects

### ISSUE THREAD

**Issue by infosec-alchemist** [unfetter-discover/unfetter#682]
- [x] Create valid travis files for all projects
- [x] Validate that the travis file is correctly running all unit tests
- [x] Determine how to run tests in our multi-container projects (unfetter-store)
- [x] Ensure that travis is responding correctly to the github account
- [x] Evaluate better ways to respond back when errors occur.
- [x] Figure out how to integrate travis with the docker images

**Comment by infosec-alchemist** [comment]
Was able to get a travis file to build in travis, that runs the docker containers.   
https://github.com/unfetter-discover/unfetter-store/pull/78
https://github.com/unfetter-discover/stix2pattern/pull/5

However, I am having trouble on my local docker instance, running the tests.  

In the travis yml, need to do a "docker exec" for each test that we want to run.

**Comment by j987987** [comment]
Something like this may work: `docker exec -it unfetter-ui npm run test --prefix /usr/share/unfetter-ui`
