### ISSUE TITLE
Question about linking analytic to ATT&CK technique

### ISSUE THREAD

**Issue by johnwunder** [unfetter-discover/unfetter#705]
I was looking to do two things:

* Adding one or more ATT&CK techniques to an existing analytic
* Adding an ATT&CK technique while creating an analytic

I can't figure out how to do either of those things from the Analytic Hub. This is probably our most critical need right now (for NH-ISAC).

**Comment by j987987** [comment]
`Adding an ATT&CK technique while creating an analytic` is possible in the current development code, at the `Relationships` step.  This the scope of this issue will be changed to the `Adding one or more ATT&CK techniques to an existing analytic` case
