### ISSUE TITLE
Default Analytic Hub to show ATT&CK techniques

### ISSUE THREAD

**Issue by johnwunder** [unfetter-discover/unfetter#706]
Right now, when an analytic has been related to ATT&CK techniques, it shows up on the far right tab and is not the default. That's the most critical data about the analytic, and so it should be the default view (i.e. when I load the analytic hub I want to see all the ATT&CK techniques for each analytic).

**Comment by infosec-alchemist** [comment]
@johnwunder , do you see people scanning through the list of analytics to find the ones of interest, and then looking at the attack technique?

Or, do you see people wanting to look at all the analytics of a particular attack technique from the beginning?  Using the filtering capability, maybe?
