### ISSUE TITLE
clean up lint errors in Unfetter-Store

### ISSUE THREAD

**Issue by infosec-alchemist** [unfetter-discover/unfetter#708]
The Unfetter-store has alot of LINT errors.  Need to go through and remove.

**Comment by mushinlogit** [comment]
@infosec-alchemist  how are you running the lint command? I do not see any lint errors on develop during a `npm run lint` run

**Comment by infosec-alchemist** [comment]
I meant "unfetter-store".  Sorry, didn't double check.

Go here "https://travis-ci.org/unfetter-discover/unfetter-store" and you can see how its being run and the results
