### ISSUE TITLE
Error building unfetter-ctf-ingest

### ISSUE THREAD

**Issue by infosec-alchemist** [unfetter-discover/unfetter#711]
While trying to build the develop build, was getting an error when building unfetter-ctf-ingest

```
Step 13/21 : RUN npm --loglevel error install
 ---> Running in d5cd7b43a6c6
npm ERR! code ENOGIT
npm ERR! No git binary found in $PATH
npm ERR!
npm ERR! Failed using git.
npm ERR! Please check if you have git installed and in your PATH
```
It is happening from the "npm --loglevel error install" part of line 22 of DockerFile.  I know this because I broke that RUN command into individual parts and got the error on the NPM error line

**Comment by mushinlogit** [comment]
@infosec-alchemist thank you for reporting this error.  Npm will sometimes use git if it needs to grab precompiled binaries or compile c native modules (usually using node-gyp).  I am not sure exactly why it is asking for git in this instance.  However I am adding `git` to the docker build.
