### ISSUE TITLE
Updating ATT&CK Content upon Release of New Versions

### ISSUE THREAD

**Issue by jburns12** [unfetter-discover/unfetter#716]
@johnwunder and I both have a need for our Unfetter instances to stay up-to-date with new releases of ATT&CK content in https://github.com/mitre/cti.

At this point, unfetter-discover-processor pulls in the content from this repository upon initialization of the Unfetter instance, but running processor.js again only adds new objects instead of updating objects that already exist. This prevents the instance from staying in-sync with changes to the ATT&CK content.

To add upon this, using something such as Github web hooks could also be beneficial in updating instances upon changes to the repo instead of needing to manually re-run processor.js.

**Comment by infosec-alchemist** [comment]
Did the ID of the attack pattern change?

**Comment by jburns12** [comment]
@infosec-alchemist - no, just the content in the object's other attributes such as name, description, etc.

**Comment by infosec-alchemist** [comment]
Okay, then processor should just be updating the changing content.

As for the webhooks, thats a good idea.  However, we wanted to prioritize the TAXII integration first.

TASK: The processor should update content, not create separate object, when run and picking up new content from Github.

**Comment by j987987** [comment]
We talked about inserting vs upserting in the past.  The issue we wanted to avoid was deleting/overriding additions or changes intentionally made in unfetter.  Most of the data we would want to stay the same would be in `metaProperties`, so it could work.

**Comment by infosec-alchemist** [comment]
I'm closing this in favor of a more comprehensive requirement at #726
