### ISSUE TITLE
The slider doesn't appear to change in Assessment Summary

### ISSUE THREAD

**Issue by infosec-alchemist** [unfetter-discover/unfetter#731]
The slider doesn't appear to be clickable in the Assessment Summary

**Comment by webiator** [comment]
@infosec-alchemist, I haven't been working on the assessments so far. Can you tell me what behavior is expected when the slider is moved, and/or if there are requirements for the assessments I can get up to speed on? I see it has five values, but it is not connected to anything on the back end.
