### ISSUE TITLE
Bars in graphs on Assessment Summary don't fit the box

### ISSUE THREAD

**Issue by infosec-alchemist** [unfetter-discover/unfetter#732]
The sophistication breakdown and % Techniques Detected by Skill do not have the bar graphs complely visible vertically, they have to be scrolled.

The y axis should be visible on the entire card

**Comment by webiator** [comment]
@infosec-alchemist, I am not seeing this behavior:

![screen shot 2018-02-20 at 7 17 24 am](https://user-images.githubusercontent.com/6414732/36423506-32d58028-160e-11e8-9f1e-86183b104dc2.png)

I'm not seeing any scrolling, or the bar charts not being completely visible. If I squeeze the screen in, at about 950 pixels wide, the Sophistication Breakdown starts to become unusable, and at 800 pixels the same goes for the % Techniques.

**Comment by webiator** [comment]
@mushinlogit informs me this was fixed with the 0.3.4 release. Closing.
