### ISSUE TITLE
Adding "external reference" or 'kill chain phase" gives an error

### ISSUE THREAD

**Issue by infosec-alchemist** [unfetter-discover/unfetter#737]
When adding an analytic, and entering the information into the "add external references" or "add kill chain phases", and clicking "attack to analytic", it adds it, refreshes the box, but automatically gives an error for each "required" box.

![image](https://user-images.githubusercontent.com/19472140/36275846-06cdf224-125a-11e8-9099-07c04ffcbdb2.png)

**Comment by j987987** [comment]
This is a hard to troubleshoot problem, since the stepper API plays a role in causing it and there isn't a straight forward way to capture when a step has been activated.
