### ISSUE TITLE
Evaluate the NGINX configurations and reduce them if possible

### ISSUE THREAD

**Issue by infosec-alchemist** [unfetter-discover/unfetter#746]
The NGINX configuration files are very similiar.

Reduce the config files to one or two files for deployment options, using environment variables or NGINX arguments

**Comment by infosec-alchemist** [comment]
The config/nginx/conf.d/default.conf is the same as config/ngins/conf.d.dockerhub

@j987987  or @mushinlogit , can we get rid of the .dockerhub config file and just use the default?

**Comment by mushinlogit** [comment]
commit removes the `conf.d.dockerhub` directory.  also syncs compose to nginx to run modes
