### ISSUE TITLE
CSC to attack pattern mapping

### ISSUE THREAD

**Issue by jaymefrye** [unfetter-discover/unfetter#754]
I'm trying to understand the logic in how the CSC Course of Action objects are being applied to the individual attack patterns. It is not obvious how some of the CSC objects listed play a part in the mitigation of the attack pattern they are listed with. 
As a shop deep into using the CIS framework this part of Unetter is very interesting to us. More transparency into the thought process for application of the COA's would be welcomed.

**Comment by infosec-alchemist** [comment]
Full disclosure, I created the mappings a year ago.  I did a quick walk through to map.  We weren't sure of any qualifiers to the relationship would help or hurt.  For instance, CSCx.y partially supports Attack Technique Y.

We have been looking for someone to publish a more comprehensive and researched connection between CSC and the attack patterns.  We can reuse any data that is published.

**Comment by jaymefrye** [comment]
Thanks for the info. And yes the qualifiers to the relationship would help when doing risk assessments. It looks like CIS is going that direction with their RAM (Risk Assessment Method) project. Unfortunately they are building their own kill chain and not utilizing the great work from Mitre et al. I'll put a bug in their ear about working with you.

**Comment by infosec-alchemist** [comment]
Closing this ticket.  If there is a better source of information, we would be happy to incorporate it.
