### ISSUE TITLE
Determine how to soften the requirement for "stix pattern" on indicators

### ISSUE THREAD

**Issue by infosec-alchemist** [unfetter-discover/unfetter#757]
Look at how to change the UI so that an analytic suggests, but does not require, a valid stix pattern language as its main language.  This barrier appears to be too high.

- [ ] @j987987  and @infosec-alchemist agree on UI change and workflow differences with @infosec-alchemist and @j987987 
- [ ]  Make changes to front end code
- [ ] Highlight if pattern is valid stix pattern
- [ ]  Make the UI show the added value with the STIX patterning in terms of translation and data object determination.

**Comment by j987987** [comment]
Many of these changes were made in previous commits.
