### ISSUE TITLE
Sophistication Breakdown chart on Assessment summary page showing same unassessed values

### ISSUE THREAD

**Issue by webiator** [unfetter-discover/unfetter#760]
Regardless of how many attack patterns are assessed, the sophistication breakdown bars are always showing the same number of unassessed attack patterns. This suggests the unassessed value is actually the total number of attack patterns per skill level, not the difference between assessed and total attack patterns. I don't know if this is intended, or what the use case would be for wanting to see a stack of assessed _plus_ total attack patterns.

**Comment by mushinlogit** [comment]
@webiator can you verify this is still an issue? @mpmmasterpeace can you look into this if it is still a problem?

**Comment by mpmmasterpeace** [comment]
I'm pretty sure this is still an issue (or a lack of understanding on my part). I'll look into it today.
