### ISSUE TITLE
fix unfetter-discover-api spec error

### ISSUE THREAD

**Issue by mushinlogit** [unfetter-discover/unfetter#764]
fix spec error in unfetter-disover-api.  Travis reports the following

```
  197 passing (4s)
  1 failing
  1) x-unfetter-assessments specific routes GET /x-unfetter-assessments/{id}/assessed-objects Returns arrays of objects assessed.:
      Uncaught AssertionError: Wrong number of assessed objects were returned.  Expected 3, received 0
      + expected - actual
      -0
      +3
      
      at Test.request.get.set.expect.expect.end (test/api/controllers/x-unfetter-assessments-dashboards.js:223:28)
      at Test.assert (node_modules/supertest/lib/test.js:179:6)
      at Server.assert (node_modules/supertest/lib/test.js:131:12)
      at emitCloseNT (net.js:1677:8)
      at _combinedTickCallback (internal/process/next_tick.js:135:11)
      at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

**Comment by mushinlogit** [comment]
@sbertrandmitre can you look at this in addition to the lint?  I confirmed this error only happens in travis and not in my local development environment. I also just learned that the travis runtime does not have node's `global` where the local did, I am unsure why that is happening.  I mocked this to fix an unrelated test.

See, `https://travis-ci.org/unfetter-discover/unfetter-store/builds/351063555#L926`

**Comment by joe-dam** [comment]
@mushinlogit  How can I tell what value is being passed in to the {id} field?

**Comment by mushinlogit** [comment]
@joe-dam you could try `console.log` in the specs themselves.  I expected `cd unfetter && docker-compose logs -f unfetter-discover-gateway` to print some access logs, but that didnt happen for me when running `npm run test` in this api directory
