### ISSUE TITLE
Examples on Swagger API page not accurate 

### ISSUE THREAD

**Issue by sbertrandmitre** [unfetter-discover/unfetter#775]
On the Unfetter "View API" page, click "Try it" for any of the APIs, and you'll see that the example text for filter, sort, and project suggest "name" as a attribute to use, when it should suggest "stix.name". 

Also, there are double back ticks around most of the example values, and copying and pasting the example text into the filter and sort fields will result in a JSON parse error.  The swagger yaml under api/swagger/path directories doesn't have any double back ticks used however, so need to find out how the standard double quote (hex 22 ASCII) gets converted to a high ascii double quote (hex 94 ascii).

**Comment by webiator** [comment]
The double quote problem may be a MacOS thing trying to be "helpful"...

**Comment by sbertrandmitre** [comment]
I think you're right, and while I'm not sure where the extended ASCII quotes are inserted, this all can be avoided by not having spaces in the filter, sort, and project example text:

description: 'Ex: {"stix.name":"AppInit DLLs"}'
