### ISSUE TITLE
Fix Swagger example filter query values

### ISSUE THREAD

**Issue by mushinlogit** [unfetter-discover/unfetter#777]
The swagger api example gives examples to values that do not exist.  Try a GET on all the stix types and make sure the sample `filter` returns a value.

Query for the distinct stix types and grab an example
`db.getCollection('stix').distinct('stix.type')`
`db.getCollection('stix').findOne('stix.type': '')`

**Comment by infosec-alchemist** [comment]
Test on
- [ ] attack patterns
- [ ] campaign
- [ ] course of action
- [ ] identity
- [ ] indicators
- [ ] intrusion set
- [ ] malware
- [ ] marking definition
- [ ] observed data
- [ ] relationship
- [ ] report
- [ ] sighting
- [ ] threat actor
- [ ] tools
- [ ] multiple
- [ ] Unfetter Assessment
- [ ] sensor
- [ ] config
