### ISSUE TITLE
Create Ansible Build/Upgrade Playbooks

### ISSUE THREAD

**Issue by infosec-alchemist** [unfetter-discover/unfetter#778]
Using Ansible, create a set of playbooks that will enable all testing and deployment scenarios.
- [x] Standard "demo" deployment should be done without ansible, requiring only "docker-compose up"
- [x] Create playbooks that support each of the deployment options (demo, production, uac)
- [x] Create playbooks to support deployments in Windows and Linux docker systems
- [x] Upgrade to latest version of software.

**Comment by j987987** [comment]
`Create a default user, if necessary` step is blocked by #652

**Comment by infosec-alchemist** [comment]
It looks like Ansible only understands Docker compose version 1 and 2, not 3.

http://docs.ansible.com/ansible/latest/guide_docker.html

This may cause issue.s

**Comment by infosec-alchemist** [comment]
Basic playbook for building and running Unfetter is complete.  Need to do the following:
- [ ] Evaluate how to include variables into sections of the modules.
- [ ] Ensure that ENV variables for DEMO and Production are setup properly
- [ ] Ensure that the dev modes are supported

**Comment by infosec-alchemist** [comment]
There is a weird problem where links might be broken if a container was started and then stopped.  Need to think about removing the hardcoded "links".  Appears they may not be necessary.

**Comment by infosec-alchemist** [comment]
Was able to get local build and pull from docker hub

Was able to build in UAC and non-UAC

Need to do the following:
- [ ] Build separate playlists for each deployment type
- [ ] Get the inventory squared away for each deployment type
- [ ] Document the variables
- [ ] Move entrypoint, exposed ports, and environment variables to Dockerfile
- [ ] See if we can remove the "links"

**Comment by infosec-alchemist** [comment]
In the updates, these are the necessary steps
- [ ] Backup of the data.  This should be AFTER the containers are running
- [ ] Create the volumes after the data is backed up
- [ ] Move the files into the volumes
- [ ] Bring the system down
- [ ] Upgrade images
- [ ] Bring it back up

**Comment by infosec-alchemist** [comment]
Having trouble with the process of upgrading the mongodb.  Bringing up mongodb with the new volume is not working.  I think its because the database is not there.

**Comment by infosec-alchemist** [comment]
Build out the common handlers so that anytime a volume is created, it will try and pull files from backups, or creates new files

- [ ] Need to split the handlers or tasks for "backup"
- [ ] Need to build restore volume from backup for certs
- [ ] Need to build restore volume from backup for mongodb
- [ ] Need to build restore volume from backup for private
- [ ] Need to build restore volume from backup for ui-private
