### ISSUE TITLE
protect assessments at the api layer

### ISSUE THREAD

**Issue by mushinlogit** [unfetter-discover/unfetter#779]
We would like to protect assessments at the API layer for the 2.1 release.  That is to say, 

Given `UAC RUN_MODE`; assessments Read by ID, Update, and Delete operations should only be exposed to certain users.  Bonus points if this works across all stix object types.

Update: this was rescoped to handle only assessments.  See comment below for most up to date logic applied.

-----
The following is a proposal;
Given `UAC RUN_MODE`, and the `unfetter-discover-api` endpoints;
* When a user requests a read by ID for any stix object type
  * Then the request should filter _on any_ three properties
    * a match on an objects `creator` field, and the current requesting users creator id (user id in mogodb)
    * a match on the objects `access` field array, and the current requesting users groups id (NOTE: access does not exist at the moment and will be populated in a future sprint) Meanwhile the filter will continue to work with or with out an `access` field array
    * a match on the objects `stix.created_by_ref`, and the Unfetter open group id

The server side filter will copy over any passed in filter parameters given to the API by the client.

## Pseudo code for applying a security filter on a mongodb request
```
    applySecurityFilter(query, request) {
        if (!query || !process.env.RUN_MODE === 'UAC') {
            return query;
        }

        const currentUserCreatorId = request.user.id;
        const currentUserOrgIds = request.user.orgs.map((el) => el.id);
        const unfetterOpenUserId = global.unfetter.openIdentity._id || '';

        const securityFilter = {
            $or: [
                { 'creator': currentUserCreatorId },
                { 'access': { $exists: true, $in: currentUserOrgIds } },
                { 'stix.created_by_ref': unfetterOpenUserId },
            ]
        };
        const filteredQuery = Object.assign({ }, ...query, ...securityFilter);
        return filteredQuery;
```

Finally some methods use an aggregation query.  Apply this security filter or a mongodb `redact` pipeline stage to the query.  Apply for a future release.
Pseudo code for [redact](https://docs.mongodb.com/manual/reference/operator/aggregation/redact/) pipeline stage.
```
var creatorId = '5a6629408d053c0041eb73e0'
db.getCollection('stix').aggregate([
    { $match: { 'stix.type': 'x-unfetter-assessment' } },
    { $redact:
        {
          $cond: {
           if: { $eq: ["$creator", creatorId] },  
           then: "$$DESCEND",
           else: "$$PRUNE"
          }  
        }
    }
])
```

Note: a creator id and created_by_ref are populated now by the Create methods for the API and processor.
 
## Steps
- [X] store unfetter open group on start up
- [X] apply security filter to read by id, delete, and update endpoints (in the `basecontroller`)
~~add `redact` to aggregation pipeline~~~

**Comment by mushinlogit** [comment]
supports parent unfetter-discover/unfetter#636

The api should not operate or return on an assessments outside the submitters group

 * A user can see an object iff
 *  the object is open to all
 *      ie, the object has a created_by_ref, with a group of unfetter open
 *  current user is admin
 *      ie, the user has the ADMIN role in the database and is seen in the request object
 *  current user has created_by_ref org
 *      ie, the object has a created_by_ref, with a group id this current user belongs

**Comment by mpmmasterpeace** [comment]
In DEMO mode, should only see assessments with a created by org of Unfetter Open.

**Comment by mushinlogit** [comment]
relates to unfetter-discover/unfetter#344
