### ISSUE TITLE
in memory cache for API

### ISSUE THREAD

**Issue by mushinlogit** [unfetter-discover/unfetter#780]
Consider adding an in-memory cache tool to facilitate queries to the API.  Possible use cases include, 

* query an in-memory cache vs mongodb for user logins
* query an in-memory cache vs mongodb for attackpatterns or other lookup data

Consider [REDIS](https://redis.io/topics/lru-cache) in memory cache w/ LRU and TTL options.  A few drivers appear to exist for Node.js

Note: this might be premature request. but it was mentioned so I am tracking the idea here for review.

**Comment by infosec-alchemist** [comment]
why is this assigned to me?
