### ISSUE TITLE
Can't select the canned assessments

### ISSUE THREAD

**Issue by infosec-alchemist** [unfetter-discover/unfetter#808]
To replicate, I 

1 Created a new assessment
2 Used the drop down to open the assessment mega form
![image](https://user-images.githubusercontent.com/19472140/37224269-f8ed037c-23a0-11e8-8e78-6cf0b6002f44.png)
3  Clicked one of the other assessments.

There is no action when I click one of those assessments.

**Comment by mushinlogit** [comment]
relates to #808

**Comment by mushinlogit** [comment]
relates to #812
