### ISSUE TITLE
Choosing an assessment hangs

### ISSUE THREAD

**Issue by infosec-alchemist** [unfetter-discover/unfetter#809]
When I create an assessment, then go to the assessment chooser

![image](https://user-images.githubusercontent.com/19472140/37224269-f8ed037c-23a0-11e8-8e78-6cf0b6002f44.png)

And then select that first assessment, it hangs

![image](https://user-images.githubusercontent.com/19472140/37224346-295e10b4-23a1-11e8-990a-561363a6a031.png)

**Comment by mushinlogit** [comment]
@infosec-alchemist thanks for reporting.  

The cause is related to #812

**Comment by mushinlogit** [comment]
@infosec-alchemist please pull the latest code, and confirm if you still see this.  It should be fixed now.

**Comment by infosec-alchemist** [comment]
The problem still occurs if I select the SAME assessment.

**Comment by mushinlogit** [comment]
@infosec-alchemist we are working to give a visual indicator to not click the current assessment type in the master list.

see unfetter-discover/unfetter#824

**Comment by infosec-alchemist** [comment]
It appears to be fixed, because we can not click the same assessment.
