### ISSUE TITLE
Adding an assessed object in the Assessment details page does not work

### ISSUE THREAD

**Issue by infosec-alchemist** [unfetter-discover/unfetter#811]
When I try to add a new assess object, I fill out all the information, hit submitt, but nothing happens

![image](https://user-images.githubusercontent.com/19472140/37225046-590f5e88-23a3-11e8-93c7-bdb8c77954c7.png)

**Comment by mushinlogit** [comment]
part of the problem is the data needed to have the attributes property unwrapped.  have a partial fix in the latest PR.  Next have to get the page to refresh state after adding a new assessed object
