### ISSUE TITLE
frames per second on assessments pages are bad

### ISSUE THREAD

**Issue by mushinlogit** [unfetter-discover/unfetter#813]
given a user in UAC runmode, angular development mode, and chrome 64;
the frames per second and responsiveness on the assessments pages are not great for my machine

low hanging things to check
[] check out the ChangeDetectionStrategy set for the component tree
[] check trackBy in our ngFor blocks
[] check template whitespace trimming

compression w/ gzip and aot will be applied in angular production mode

**Comment by mushinlogit** [comment]
see a good [performance checklist](https://github.com/mgechev/angular-performance-checklist)

**Comment by mpmmasterpeace** [comment]
There are no issues when testing in prod mode.
Some of the above may be worth doing, but are probably not candidates for this release.
