### ISSUE TITLE
Remove relationships from persisted STIX objects, they should be stored as separate "Relationship" objects

### ISSUE THREAD

**Issue by infosec-alchemist** [unfetter-discover/unfetter#82]
<a href="https://github.com/dev-jitsu"><img src="https://avatars.githubusercontent.com/u/24814771?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dev-jitsu](https://github.com/dev-jitsu)**
_Tuesday Jan 31, 2017 at 15:32 GMT_
_Originally opened as https://github.com/iadgov/cti-stix-services/issues/111_

----

For example, an Intrusion Set has relationships to Identities, Threat Actors, and Attack Patterns.  Currently these are captured both as separate "Relationship" objects (good), but also also array properties on the Intrusion Set itself (bad).  These array properties should be removed.

Fix "list", "details", "edit", and "new" pages for 
-Intrusion Set
-Campaign
-Sighting

**Comment by dev-jitsu** [comment]
This was fixed as part of another issue.
