### ISSUE TITLE
When I create a new object type in the assessment details, it doens't show up

### ISSUE THREAD

**Issue by infosec-alchemist** [unfetter-discover/unfetter#823]
When I create a new assessed object from the assessment details page, the new object does not show up unless I refresh the browser.

**Comment by webiator** [comment]
I was able to create an assessment, and, after hitting Save, its summary page came up right away. It also appeared at the top of the master list dialog.

One weird behavior, though, was that if I hit the Edit button (either on the options dropdown or on the master list dialog), after many seconds, the summary page reappeared. I did not get an edit page. In this case, I did have to refresh the browser in order for the Edit button to work.
