### ISSUE TITLE
Master list dialog rows for item currently in view should be unselectable(?)

### ISSUE THREAD

**Issue by webiator** [unfetter-discover/unfetter#824]
The item should either
- Not be displayed at all (I'm not thrilled with this idea)
- Should be there, but not selectable
  - It should be easily identifiable as unselectable (highlighted and/or dimmed and/or styled differently)
  - Cursor should not be a pointer

The master list dialog itself is agnostic to the data being displayed, and the route displaying it (all these things are deferred to the component calling for its display), and the data in the table is provided by a datasource the user provides. So this mean the datasource will have to provide this information for each row it returns. To make it backward-compatible, recommending the sources _not change_ the data provided by any service it calls (since the service couldn't possibly know what page you are on, anyway), but that it updates the data returned with additional properties.

**Comment by mushinlogit** [comment]
@webiator I just realized, we could also code the onCell call back to just check and not try to route when we detect the selected element is the same as the current.  The draw back to this would mean every place we code the onCell callback would need to do the check.  And this alone still does not indicate to the user a disabled state

**Comment by webiator** [comment]
Right, that check should still be done, but I want to at least give the user some visual indicator that the row in the table is the same as what is currently being displayed.

**Comment by mushinlogit** [comment]
@webiator good call. Who will do the check, will it be included in this issues PR?

**Comment by webiator** [comment]
Modified it so that the cell has different style if it is currently on display, and cannot be clicked.
