### ISSUE TITLE
When editing an assessment, the pie chart dissappears on the summary page

### ISSUE THREAD

**Issue by infosec-alchemist** [unfetter-discover/unfetter#828]
When I edit an assessment, and I get to the final summary page, the space for the "phase rating" is there.   But the pie chart disappears.

**Comment by mpmmasterpeace** [comment]
This should probably be a summary rollup, but that is not implemented. The correct behavior for now is to remove the chart on that page.

**Comment by infosec-alchemist** [comment]
If you click directly to the summary page, the pie cart is on there

**Comment by mpmmasterpeace** [comment]
@infosec-alchemist To be clear, are you seeing this after I merged this PR into the develop branch?
