### ISSUE TITLE
Update registration process

### ISSUE THREAD

**Issue by johnwunder** [unfetter-discover/unfetter#839]
I think we could streamline setting up organizations a bit if users were prompted during registration to self-select an organization. The org admin (or site admin) could then approve them joining that org, as normal...it would just keep them from having to know to go into their settings to do it.

**Comment by infosec-alchemist** [comment]
In general, find a way to streamline the user login where a user has to select their organization. 

I do not recommend letting a person select the organization during registration, because that gives outside people inside information into what organizations are using the tool.

**Comment by j987987** [comment]
That functionality already exists during registration.  If security is a concern, it can be removed and be replaced with a notification that will occur after their account is approved.

**Comment by infosec-alchemist** [comment]
Yes, the organization should not be a drop down.  We should have users type their organization, and let the approvers select from the approved list.

**Comment by j987987** [comment]
I edited the title

From: `Prompt users to select an organization when they create an account`
To: `Update registration process`

To reflect the scoping of this issue.

The plan is do the following:
- Add a box where people can write why they want to use unfetter
- Add the ability for users to manually write organizations
- Add ability in the admin dashboard to approve people to organizations they asked for (will be a manual process)
- General improvements to registration page and admin dashboard
