### ISSUE TITLE
Add the CTF demo data to the processor

### ISSUE THREAD

**Issue by infosec-alchemist** [unfetter-discover/unfetter#857]
Move the preloaded CTF demo data to the processor, so that all demo data is used through a single docker container.  This will help streamline the docker compose files, and will help with integrating the TAXII client into the Processor.

**Comment by mushinlogit** [comment]
current data in the ctf-ingest project is sample data to test translating data into stix and processor ingestable form.  Sample data is for current CTF is also already in the processor.  Closing this issue, unless there is something specific we should address
