### ISSUE TITLE
In Assessment Create, object risks are "gray" even when already assessed

### ISSUE THREAD

**Issue by infosec-alchemist** [unfetter-discover/unfetter#858]
When an object is assessed, but appears in a follow on kill chain, its color is Gray rather than properly scored.

it is also not part of the scored value.  Need to determine if this went out with the last release.

**Comment by infosec-alchemist** [comment]
I'm seeing that some object, which I have not even assessed, are getting a default value in the drop down box.  But not in every case

![image](https://user-images.githubusercontent.com/19472140/37618358-65eefa5a-2b8c-11e8-9da0-29258a25310e.png)

**Comment by mushinlogit** [comment]
OBE, related to unfetter-discover/unfetter#962
