### ISSUE TITLE
assessment summary graphs not rendering

### ISSUE THREAD

**Issue by infosec-alchemist** [unfetter-discover/unfetter#861]
When entering assessments after logging in, and the default assessment is displayed on the summary page, two of the three graphs do not render values.  when I move the slider, then will then render

![image](https://user-images.githubusercontent.com/19472140/37660320-847c6a6a-2c28-11e8-82bf-396d74017428.png)

**Comment by mpmmasterpeace** [comment]
Merged with unfetter-discover/unfetter-ui#336
