### ISSUE TITLE
App 'forgets' that I'm logged in ~every 15 minutes

### ISSUE THREAD

**Issue by mpmmasterpeace** [unfetter-discover/unfetter#867]
When using Unfetter and logging in with github credentials, after a few minutes I will have to re-sign in to continue using the application. It's about 15 minutes.

This also causes a redirect, but that may be related to another issue. Perhaps #868.

**Comment by mushinlogit** [comment]
@mpmmasterpeace 

I am not seeing this;

1. I brought up docker-compose.deploy.yml
2. Visited an assessment
3. let the page sit
4. was not redirected automatically
5. saw there console log messages
```
disconnect from datasource
08:51:41.747 main.87c7060c2820b2a07357.bundle.js:1 Token successfully refreshed
09:02:11.895 main.87c7060c2820b2a07357.bundle.js:1 Token successfully refreshed
```
6. click on the full results tab in that assessments and was routed correctly

@j987987 should we add timestamps to the token refresh log statement.  Also in Chrome you can add timestamps to the log statements

**Comment by mpmmasterpeace** [comment]
@webiator and I have both seen this using similar steps to yours. I will see if I can narrow down what's happening.

**Comment by infosec-alchemist** [comment]
There is a 15 minute timeout as per design.  Are you all taking that into account?

**Comment by mpmmasterpeace** [comment]
I'm going to close. Did not see this yesterday. May be OBE.
