### ISSUE TITLE
The new master copy does not work

### ISSUE THREAD

**Issue by infosec-alchemist** [unfetter-discover/unfetter#869]
It appears that sometimes, when Unfetter is first run, the database doesn't properly load.  We need a better way for Processor to wait for the database to start up?

I'm not sure what caused this error.

**Comment by j987987** [comment]
The processor was completely rewritten a couple months ago and is coded to attempt to connect to mongo every 5 seconds, up to 10 attempts.  It would be trivial to adjust these variables.

The processor code itself is not run until the connection to mongo is successful.

`docker logs unfetter-discover-processor` would be helpful

**Comment by j987987** [comment]
Here is what I observed:

- Processor ran fine
- API tried to start
- New code in the API that looks for organizations and configurations before starting up failed to find them, because processor didn't load them yet, so the API didn't start
- Restarting the stack launched the API fine

**Comment by mushinlogit** [comment]
as a longer term fix; suggest adding a processor loading latch state into mongo, then we can poll for it on startup

**Comment by j987987** [comment]
The long term fix is captured in https://github.com/unfetter-discover/unfetter/issues/871

**Comment by j987987** [comment]
https://github.com/unfetter-discover/unfetter-store/pull/122
