### ISSUE TITLE
Unhelpful error with required field on Stix pages when creating certain new objects

### ISSUE THREAD

**Issue by mpmmasterpeace** [unfetter-discover/unfetter#875]
Creating a new Stix object from the Stix pages that has and External Reference can be problematic.
If a user adds an external reference, but doesn't provide a Source Name, there will be an error when saving. Only by viewing the console would you see that the problem is that Source Name is required.
Popup to user is: "Error: error" or something similar.

This field should be clearly marked and validated as required.

**Comment by j987987** [comment]
The particular example of external references would be quite annoying to fix without reactive forms, so I suggest the scope of the issue is narrowed.
