### ISSUE TITLE
Creating a new work product in threat dashboard, the date picker is using the wrong format

### ISSUE THREAD

**Issue by mpmmasterpeace** [unfetter-discover/unfetter#877]
On the threat dashboard when creating a new work product, date picker does not use correct format. It looks like it’s expecting d/m/yyyy; pop-up uses m/d/yyyy.
What is wrong is the expected format, not what the pop-up is doing. Other date pickers throughout the  dashboards do not use this format.

**Comment by webiator** [comment]
Even the aria-label for the fields claims it's supposed to be m/d/y. The date format property in the component is the culprit.
