### ISSUE TITLE
Threat Dashboard hangs browser when trying to get a deleted last work product

### ISSUE THREAD

**Issue by mpmmasterpeace** [unfetter-discover/unfetter#888]
Threat Dashboard loads the last Work Product (that you worked on?).
If, for some reason, that Work Product is deleted (by someone else in your org?), the page will be stuck on a loading icon. It also completely locks up that browser tab. Can't close it. Have to close the whole browser -- actually have to Force Kill Chrome(!!)

I experienced this when I deleted a work product from Mongo that happened to be my last work product touched.

**Comment by mushinlogit** [comment]
This is an old issue and may have been fixed.  I created a single workproduct, deleted the reports and workproduct references from mongo.  When visiting the threat dashboard app icon I am routed to a create page.  
When clicking the app icon you are routed to the last modified, this last modified information is queried for every time, so the flow is designed to not fail in the above case.
Marking irreproducible and closing
