### ISSUE TITLE
Travis build fails for unfetter-store when including the discover-processor linting

### ISSUE THREAD

**Issue by mpmmasterpeace** [unfetter-discover/unfetter#898]
Currently commented out in the .travis.yml file:
- docker exec -it unfetter-discover-processor npm run lint

npm run lint runs fine in a local dev environment however in the Travis docker environment it gives the following error:

$ docker exec -it unfetter-discover-processor npm run lint
Error response from daemon: **Container 537511ab745766787dd6cf60a5d6c9f7d28d2f599e525d767312f57d06daabb1 is not running**
The command "docker exec -it unfetter-discover-processor npm run lint" exited with 1.

**Comment by infosec-alchemist** [comment]
Okay, I think I need to do a "Docker run" to run a specific copy of the container that only does an NPM run Lint.

**Comment by j987987** [comment]
I think this has been resolved.
