### ISSUE TITLE
Use websocket connection to get latest sightings data for Event Dashboard

### ISSUE THREAD

**Issue by mpmmasterpeace** [unfetter-discover/unfetter#902]
Will need to pull in sightings data from store whenever new data is added.
Will also need additional calls to get information referenced by sightings: indicators -> attack-patterns -> Intrusion Set -> Threat Actor

**Comment by j987987** [comment]
This would be accomplished by adding a link for sightings in the `// Notify org members` section of the API's basecontroller `add()` function, and making any other changes as needed.

As long as the STIX document has an organization, people in that organization that are receiving notifications should be notified.
