### ISSUE TITLE
Flesh out or Mock up Related Panel for Event Dashboard

### ISSUE THREAD

**Issue by mpmmasterpeace** [unfetter-discover/unfetter#903]
There are two components here:

- My Security Gaps
   - Some kind of chart based on an assessment; likely a dummied chart to start
- Threat Reports
   - List of Titles of Threat Reports in the system that link to the reports

**Comment by infosec-alchemist** [comment]
I'm going to move this since we are slowing down on the Events dashboard until we get some good takers
