### ISSUE TITLE
datepicker swaps day/month in threat-report-editor create workflow

### ISSUE THREAD

**Issue by tigerbeard** [unfetter-discover/unfetter#912]
When typing in or choosing dates, the UI swaps the day/month numbers in the Date From and Date To fields.

To recreate, navigate to the Threat Dashboard, select the arrow for work products and click Create
On the Create Work Product page, select a day number larger than 12 and it will report an invalid date error. For day numbers under 13, it swaps the day/month numbers.
This happens whether selecting a date with the date picker or typing in a date.

In the screenshots, I pick March 6th, 2018, the page rewrites to June 3rd, 2018, which the date picker reflects.

---
<img width="617" alt="screen shot 2018-03-29 at 3 43 22 pm" src="https://user-images.githubusercontent.com/126162/38112684-57fb578e-3368-11e8-89c7-95520254366d.png">

---
<img width="373" alt="screen shot 2018-03-29 at 3 43 45 pm" src="https://user-images.githubusercontent.com/126162/38112777-93b3f89e-3368-11e8-8739-f3e79fdb1df3.png">

---
I believe it's a bug somewhere around here:
> unfetter-ui/src/app/threat-dashboard/threat-report-editor/threat-report-editor.component.html

**Comment by infosec-alchemist** [comment]
Thanks for catching that.  We will work it into the next release.

**Comment by j987987** [comment]
Thanks for the feedback, tigerbeard.

This was fixed in #877 and is merged into our development branch, and will be merged into our master branch in a few weeks.  Closing this issue.
