### ISSUE TITLE
Stix pages for Courses of Action has Unstable Add Label functionality

### ISSUE THREAD

**Issue by mpmmasterpeace** [unfetter-discover/unfetter#969]
# Problem
The Courses of Action page has a few issues related to adding a Label to a Course of Action.
## New Course of Action

- For a new CoA adding one label seems fine, but adding more sometimes copies an existing label's value.

- Also for a new CoA, removing a label can remove more than one label if the labels have the same value (for example if you made 3 labels with value 'a', clicking REMOVE on one of them can remove 2 or 3 labels.
## Existing Course of Action
- For an existing CoA, the +ADD label button has no effect

**Comment by j987987** [comment]
I expanded the scope of this issue.
- Add labels to all STIX CRUD pages as its a common property
- Add aliases to STIX CRUD pages that should have it
- Remove existing labels and aliases components in favor of generic stix-text-array component
